### PR TITLE
feat: Move alembic config into mealie package for easier distribution

### PR DESCRIPTION
**Pull request by chishm**
## What type of PR is this?

- cleanup
- feature

## What this PR does / why we need it:

The Alembic configuration and database migration scripts are moved inside the mealie Python package. This means they will be always available, in a consistent location. The advantages are:
* No extra step needed during mealie installation to add the Alembic configuration and scripts.
* No need to guess where the configuration is, so the `ALEMBIC_CONFIG_FILE` environment variable doesn't need to be set, ever. I've left it in as an option for people who still want to use it.

As a side effect, `ruff` (specifically `isort`) no longer thinks `alembic` is a project (["LOCALFOLDER"](https://pycqa.github.io/isort/docs/configuration/custom_sections_and_ordering.html)) package, so the imports of `alembic` are moved to the third-party group.

## Which issue(s) this PR fixes:

This is one task from discussion #4322.

## Testing

I built and ran the Docker container, then made sure the database migration still occurred.

I created a database change following the instructions in [database-changes.md](https://docs.mealie.io/contributors/developers-guide/database-changes/).

### CODE REVIEW

**Comment by chishm** [comment]
I'm waiting on #4551 to be reviewed and merged before I rebase this PR for merge.

But if someone wants to review this one first, I'm happy to rebase now.

**Review by hay-kot — DISMISSED** [review]
LGTM, please rebase and I'll get it merged!

**Comment by chishm** [comment]
Thank you for the review. I've rebased and re-run the manual tests (creating a database migration, building and running the Docker image) and I'm happy for this to be merged.

**Review by hay-kot — APPROVED** [review]

**Comment by tecosaur** [comment]
A quick question, after this change does this patch still look relevant? https://github.com/NixOS/nixpkgs/blob/master/pkgs/by-name/me/mealie/package.nix#L94-L108

**Comment by chishm** [comment]
> A quick question, after this change does this patch still look relevant? https://github.com/NixOS/nixpkgs/blob/master/pkgs/by-name/me/mealie/package.nix#L94-L108

Taking a look, I think lines 95-98 are still relevant, but 100-107 shouldn't be necessary any more.

**Pull request merged**
