### PR TITLE
docs: Fix Formatting

### PR DESCRIPTION
**Pull request by michael-genson**
## What type of PR is this?

_(REQUIRED)_

- documentation

## What this PR does / why we need it:

_(REQUIRED)_

Fixes broken docs formatting.

## Which issue(s) this PR fixes:

_(REQUIRED)_

N/A

## Special notes for your reviewer:

_(fill-in or delete this section)_

## Testing

_(fill-in or delete this section)_

Built docs server.

### CODE REVIEW

**Review by Kuchenpirat — DISMISSED** [review]
👍

**Review by Kuchenpirat — COMMENTED** [review]
If we are already in the docs, could you task docs to have it generate the api?
There should be quite some changes with the whole renaming the recipe create paths

**Comment by michael-genson** [comment]
Yup, done!

**Review by Kuchenpirat — APPROVED** [review]
👍

We might at one point put the docs api gen in a workflow. This gets forgotten all the time.

**Pull request merged**
