### PR TITLE
feat: Support additional compression algorithms

### PR DESCRIPTION
**Pull request by HowRuck**
## What type of PR is this?
- feature

## What this PR does / why we need it:

This PR introduces support for newer compression algorithms (Brotli and Zstd) in addition to the currently supported Gzip. By dynamically selecting the best compression algorithm based on the Accept-Encodings header from the request, this change aims to improve overall performance, particularly in low bandwidth scenarios

## Which issue(s) this PR fixes:
Not really any issue per se, it just improves performance a little.

## Special notes for your reviewer:

I've done a quick scan over the `starlette-compress` library used here, as it is still pretty new and very small. I haven't found any issues with it. It literally just chooses the best compression and compresses the content using standard libraries. Feel free to have another look around, in case I missed anything :-)

## Testing

I've been using this change in my private mealie instance for the last week without any issues.

### CODE REVIEW

**Comment by hay-kot** [comment]
Do you have any benchmarks for the performance difference here? If we’re going to add a dependency id be interested to know if the tradeoff is worth it. 

In my mind setting up your reverse proxy to handle compression might be a better bet.

**Comment by HowRuck** [comment]
> Do you have any benchmarks for the performance difference here? If we’re going to add a dependency id be interested to know if the tradeoff is worth it.

I've done some *very* basic testing, and so far I am coming to the conclusion that adding a new dependency is probably not worth it (benefits are there but relatively minor). The solution below, however, might be an interesting alternative :thinking: 
I'll do some more testing in the coming days if needed. 

> In my mind setting up your reverse proxy to handle compression might be a better bet.

That would most definitely be the best bet :+1: 

The only problem with this is that traefik, or most other reverse proxies, don't compress data that is already compressed. A good solution for this would be to add an environment variable (defaulting to `true`) that controls whether gzip compression is active or not. If not, compression can then be handled by the reverse proxy.

This would enable the use of modern compression algorithms without adding additional dependencies, and would also allow a nice separation of concerns while increasing flexibility. 

What would you think of this approach? :thinking:

**Comment by hay-kot** [comment]
> A good solution for this would be to add an environment variable (defaulting to true) that controls whether gzip compression is active or not. If not, compression can then be handled by the reverse proxy.

This sounds good to me, Sorry for the delay!

**Comment by michael-genson** [comment]
Converted to draft since it looks like the changes were reverted. Once it's ready feel free to switch it back!

**Comment by hay-kot** [comment]
Closing for now, feel free to reopen or create a new PR with the changes discussed. Thanks!

**Pull request closed without merging**
