### PR TITLE
feat: email password reset link directly from admin dashboard

### PR DESCRIPTION
**Pull request by Kuchenpirat**
## What type of PR is this?

- feature

## What this PR does / why we need it:

This adds the option to directly send an email with the password reset link to the email adress of the user. 

Most users will propably find the "Forgot Password" field on the login screen themselves, but some not so tech savy will just call their e.g. family member that hosts mealie and aks them to fix it. 

## Which issue(s) this PR fixes:

None

## Special notes for your reviewer:

- This does currently not test whether email is enabled. But this does seem to be common for other buttons as well. 
- The token that is send per email is not the same as the one displayed in the dashboard, because the email function generates a new token. Both work. 

## Testing

Tested with the mailpit service. ~~Mealie does generate the link a bit false (port 8080 instead of 3000) but if the user has email configured correctly, this sould not fail as it uses the normal forgot-password api endpoint.~~

### CODE REVIEW

**Review by cmintey — APPROVED** [review]

**Comment by boc-the-git** [comment]
@Kuchenpirat any chance you can add before and after images please?

**Comment by boc-the-git** [comment]
The mail pit issue, does that relate just to the Dev container?

**Comment by Kuchenpirat** [comment]
> The mail pit issue, does that relate just to the Dev container?

Yep, that is only mailpit. I just pushed another commit setting the BASE_URL in the taskfile which fixes that.

**Comment by Kuchenpirat** [comment]
Screenshots: 

Before: 
image


After: 
image

**Review by boc-the-git — APPROVED** [review]
LGTM 🚀

**Pull request merged**
