### PR TITLE
feat: Shopping list UI overhaul - increase list item width

### PR DESCRIPTION
**Pull request by Wetzel402**
## What type of PR is this?

- feature

## What this PR does / why we need it:

- A fix for long list item names

## Which issue(s) this PR fixes:

https://github.com/mealie-recipes/mealie/pull/4077

## Testing

Tested in dev container

### CODE REVIEW

**Review by Kuchenpirat — APPROVED** [review]
First one done 👍

**Comment by Wetzel402** [comment]
Can the PR be reopened?  I have changes for you to test.

**Comment by Kuchenpirat** [comment]
i don't think so. Just open a new PR.

**Comment by Wetzel402** [comment]
Opened...
https://github.com/mealie-recipes/mealie/pull/4244

**Pull request merged**
