### PR TITLE
feat: add meal plan to shopping list

### PR DESCRIPTION
**Pull request by michael-genson**
## What type of PR is this?

_(REQUIRED)_

- feature

## What this PR does / why we need it:

_(REQUIRED)_

Adds a new context menu to meal plans that lets you add the entire day to a shopping list:
image

Each recipe's ingredients can be modified just like when you add them individually (except now you can see the recipe name):
image

(note that on single recipes the title is still left off):
image

Additionally:
- the context menu only appears if there are recipes (see first screenshot)
- note-only recipes are ignored (see first screenshot)
- if a recipe appears on the same day more than once, it only appears once on the shopping list dialog, but the scale is incremented per recipe instance

## Which issue(s) this PR fixes:

_(REQUIRED)_

Closes FR https://github.com/mealie-recipes/mealie/discussions/1899

## Special notes for your reviewer:

_(fill-in or delete this section)_

This PR makes not being able to view/modify the scale in the "add to shopping list" dialog a bit more annoying, since it's hard to tell if the meal plan recipe was added the correct number of times (it is, but reassurance is nice). I'll probably work on a PR for that soon.

## Testing

_(fill-in or delete this section)_

Manually :)

### CODE REVIEW

**Review by boc-the-git — COMMENTED** [review]
I put my hands up as not a JS expert.. but I've looked through all this and nothing jumps out to me as being a critical issue.

The only thing I can think to ask before approving @michael-genson is whether you've tested some very complex scenarios and ensuring they get all the correct quantity of ingredients onto the list. I'm thinking something like 10 meals on one day, where some recipes have no ingredients, some have many, some have scaling, some don't, etc..
Happy to hit approve if you confirm you've covered that sort of thing in your testing.

**Comment by michael-genson** [comment]
@boc-the-git you should be able to pull the repo locally and give it a whirl. If you're using VSCode the GitHub PR extension makes it super easy:
image

Otherwise - I tried a few of those but you raise some other good edge cases, I can test those out

**Comment by boc-the-git** [comment]
> @boc-the-git you should be able to pull the repo locally and give it a whirl. 

Yea, not opposed to giving it a whirl myself, but it probably wouldn't be before Sunday.

**Comment by Belgadon** [comment]
On a side note: I think it would be a good feature to also add the entire selected date range to the shopping list at once.
Thoughts?

**Comment by boc-the-git** [comment]
@michael-genson one thing I note.. the experience is not great when you're not using ingredient amounts.. something I'm not yet using in my Prod instance.
Instead of an ingredient amount of "1" and item "egg", I simply have the ingredient "1 egg". In my testing, if I have that recipe twice on the same day and add them to the shopping list, the string "1 egg" is what is displayed on the confirmation screen - though in practice it _does_ add a quantity of 2, to "1 egg" on the shopping list. 
Represented by "1 vanilla pod" in the images I'll attach below.

So the above is probably a user friendliness issue - the right stuff seems to be ending up on the shopping list and my only suggestion might be to include a quantity of _the recipe_ on the confirmation.. low priority.

A potentially bigger issue depending on people's use case, the "linked recipes" on the shopping list are wrong. I've only ended up with one in the list despite having added 5 meals with 3 distinct recipes.

Images show meal plan, 'add to list' prompt, and the shopping list itself.
image
image
image

(oh, for ease, the two recipes included twice, only had one ingredient.. the other recipe had 3)

**Comment by michael-genson** [comment]
> the experience is not great when you're not using ingredient amounts

That's generally true for anything involving recipe scaling. I would expect anyone using the feature to have parsed their recipes. If there are ways to improve the experience for non-parsed recipes (other than making parsing easier) that's worth a discussion on a more general PR

> my only suggestion might be to include a quantity of the recipe on the confirmation

Totally agree, I think there's a FR open for that which I was planning on tackling after this PR is merged

> I've only ended up with one in the list despite having added 5 meals with 3 distinct recipes

Are you able to reproduce this? I tried adding a bunch of different recipes all of different quantities and I can't seem to end up with the wrong number of recipes

**Comment by michael-genson** [comment]
While trying to reproduce the issue you were having, I accidentally clicked on the individual recipe's context menu (which obviously will only add the recipe once). Is that possibly what you did?

Related to that, I found a bug where sometimes that would throw an error because of a null recipe ref, which is now fixed

**Comment by boc-the-git** [comment]
> While trying to reproduce the issue you were having, I accidentally clicked on the individual recipe's context menu (which obviously will only add the recipe once). Is that possibly what you did?

Definitely not. Will share specifics below.

> Related to that, I found a bug where sometimes that would throw an error because of a null recipe ref, which is now fixed

Nice!
Note the test I'll describe below, I'm still using your branch as of yesterday, i.e. without this fix.

> Are you able to reproduce this? I tried adding a bunch of different recipes all of different quantities and I can't seem to end up with the wrong number of recipes

The test I previously documented was actually the 2nd time I'd experienced it, though it was the first in a "controlled test" - the first time I assumed I might have done something wrong.
Done just now, these images are an exact sequence of events, showing an empty shopping list, adding a day, getting the confirmation that implies 3 different recipes (which we know is actually _5 meals_), and in this case only 2 have ended up as linked recipes (the ingredients are correct, only the recipes are wrong).

image
image
image
image
image

The 3 recipes I'd imported are these, then I just deleted ingredients to get them to the state you've seen in screenshots (including setting quantities on one of them). Long shot, but giving the specifics in case something about them is relevant.
https://www.recipetineats.com/parmesan-roasted-green-beans/
https://www.recipetineats.com/creme-brulee/
https://www.recipetineats.com/chicken-pad-thai/

Note, I'm going to be away for a few days, so will have limited ability to communicate and effectively no ability to fiddle with things.

**Comment by boc-the-git** [comment]
These are the logs btw.. doesn't look to be anything too interesting.

```
mealie-dev   | INFO:     192.168.69.1:44434 - "GET /favicon.ico HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:44434 - "GET /api/app/about HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:44434 - "GET /api/app/about HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:44434 - "GET /sw.js HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:48452 - "POST /api/auth/token HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:48452 - "GET /api/users/self HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:48472 - "GET /api/media/users/b95a9ef8-360f-47e1-8ed9-fbc037cdf5f8/profile.webp?cacheKey=1234 HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:48452 - "GET /api/users/self/group HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:48464 - "GET /api/groups/cookbooks?page=1&perPage=-1&orderBy=position&orderDirection=asc HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:48472 - "GET /api/organizers/tags?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:48464 - "GET /api/organizers/categories?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:48494 - "GET /api/recipes?page=1&perPage=64&orderBy=created_at&orderDirection=desc&paginationSeed=1698782828443&searchSeed=1698782828443&search=&requireAllCategories=false&requireAllTags=false&requireAllTools=false&requireAllFoods=false HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:48488 - "GET /api/organizers/tools?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:48452 - "GET /api/foods?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:48452 - "GET /api/media/recipes/880cb379-0dfd-4048-bf70-81fd3b19ba31/images/min-original.webp?rnd=1&version=emNT HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:48494 - "GET /api/media/recipes/584892ce-421f-4277-9b6f-9aaf5350bd79/images/min-original.webp?rnd=1&version=IWFR HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:48488 - "GET /api/media/recipes/655fd2ef-493e-4a29-8461-2c94a91f7a2e/images/min-original.webp?rnd=1&version=jIU2 HTTP/1.1" 200 OK
mealie-dev   | INFO:     127.0.0.1:54720 - "GET /api/app/about HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:43074 - "GET /sw.js HTTP/1.1" 304 Not Modified
mealie-dev   | INFO:     127.0.0.1:59776 - "GET /api/app/about HTTP/1.1" 200 OK
mealie-dev   | INFO:     127.0.0.1:37014 - "GET /api/app/about HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:53804 - "GET /_nuxt/63704b3.js HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:53804 - "GET /api/groups/shopping/lists?page=1&perPage=-1 HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:53804 - "GET /_nuxt/img/shopping-cart.1ff7637.svg HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:53812 - "GET /_nuxt/fc18e3c.js HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:53804 - "GET /_nuxt/1076772.js HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:53818 - "GET /_nuxt/88b172b.js HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:53824 - "GET /api/groups/labels?page=1&perPage=-1 HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:53812 - "GET /api/groups/labels?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:53818 - "GET /api/units?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:53804 - "GET /api/groups/shopping/lists/0f4c6e3d-483a-4ee5-8b00-91029116f3d4 HTTP/1.1" 200 OK
mealie-dev   | INFO:     127.0.0.1:35104 - "GET /api/app/about HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:53804 - "GET /api/groups/shopping/lists/0f4c6e3d-483a-4ee5-8b00-91029116f3d4 HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:53804 - "PUT /api/groups/shopping/items/d379a576-4cf0-4ada-9dd4-44de467159ba HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:53804 - "GET /api/groups/shopping/lists/0f4c6e3d-483a-4ee5-8b00-91029116f3d4 HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:53804 - "PUT /api/groups/shopping/items/80e276e5-0cec-48fb-8902-a9ce4be361fb HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:53804 - "GET /api/groups/shopping/lists/0f4c6e3d-483a-4ee5-8b00-91029116f3d4 HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:53804 - "PUT /api/groups/shopping/items/aea4c63a-3e96-49de-8116-fbaeecd097a8 HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:53804 - "GET /api/groups/shopping/lists/0f4c6e3d-483a-4ee5-8b00-91029116f3d4 HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:53804 - "PUT /api/groups/shopping/items/1cadd9ff-868d-4b0e-a735-f6d3e65f55b0 HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:53804 - "GET /api/groups/shopping/lists/0f4c6e3d-483a-4ee5-8b00-91029116f3d4 HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:53804 - "PUT /api/groups/shopping/items/ae697dee-ab43-4e44-b0af-b52fe6a06861 HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:53804 - "GET /api/groups/shopping/lists/0f4c6e3d-483a-4ee5-8b00-91029116f3d4 HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:49694 - "GET /api/groups/shopping/lists/0f4c6e3d-483a-4ee5-8b00-91029116f3d4 HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:53804 - "DELETE /api/groups/shopping/items?ids=d379a576-4cf0-4ada-9dd4-44de467159ba&ids=aea4c63a-3e96-49de-8116-fbaeecd097a8&ids=80e276e5-0cec-48fb-8902-a9ce4be361fb&ids=1cadd9ff-868d-4b0e-a735-f6d3e65f55b0&ids=ae697dee-ab43-4e44-b0af-b52fe6a06861& HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:53804 - "GET /api/groups/shopping/lists/0f4c6e3d-483a-4ee5-8b00-91029116f3d4 HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:53804 - "GET /_nuxt/88e54c5.js HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:49710 - "GET /_nuxt/610b571.js HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:49694 - "GET /_nuxt/7253643.js HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:49694 - "GET /api/groups/mealplans?page=1&perPage=-1&start_date=2023-11-01&end_date=2023-11-07 HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:49694 - "GET /api/media/recipes/655fd2ef-493e-4a29-8461-2c94a91f7a2e/images/min-original.webp?rnd=1&version=abc123 HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:49710 - "GET /api/media/recipes/880cb379-0dfd-4048-bf70-81fd3b19ba31/images/min-original.webp?rnd=1&version=abc123 HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:53804 - "GET /api/media/recipes/584892ce-421f-4277-9b6f-9aaf5350bd79/images/min-original.webp?rnd=1&version=abc123 HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:49710 - "GET /api/groups/shopping/lists?page=1&perPage=-1 HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:49710 - "GET /api/groups/labels?page=1&perPage=-1 HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:40164 - "GET /api/groups/shopping/lists/0f4c6e3d-483a-4ee5-8b00-91029116f3d4 HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:40174 - "GET /api/groups/shopping/lists/0f4c6e3d-483a-4ee5-8b00-91029116f3d4 HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:40174 - "GET /api/groups/shopping/lists/0f4c6e3d-483a-4ee5-8b00-91029116f3d4 HTTP/1.1" 200 OK
mealie-dev   | INFO:     127.0.0.1:56012 - "GET /api/app/about HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:40174 - "GET /api/groups/mealplans?page=1&perPage=-1&start_date=2023-11-01&end_date=2023-11-07 HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:50492 - "GET /api/groups/shopping/lists?page=1&perPage=-1 HTTP/1.1" 200 OK
mealie-dev   | INFO:     127.0.0.1:38628 - "GET /api/app/about HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:35610 - "GET /api/recipes/creme-brulee-french-vanilla-custard HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:35610 - "GET /api/recipes/pad-thai HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:35610 - "GET /api/recipes/parmesan-roasted-green-beans HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:41034 - "POST /api/groups/shopping/lists/0f4c6e3d-483a-4ee5-8b00-91029116f3d4/recipe/584892ce-421f-4277-9b6f-9aaf5350bd79 HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:41044 - "POST /api/groups/shopping/lists/0f4c6e3d-483a-4ee5-8b00-91029116f3d4/recipe/655fd2ef-493e-4a29-8461-2c94a91f7a2e HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:41058 - "POST /api/groups/shopping/lists/0f4c6e3d-483a-4ee5-8b00-91029116f3d4/recipe/880cb379-0dfd-4048-bf70-81fd3b19ba31 HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:41058 - "GET /api/groups/shopping/lists?page=1&perPage=-1 HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:41058 - "GET /api/groups/labels?page=1&perPage=-1 HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:44948 - "GET /api/groups/shopping/lists/0f4c6e3d-483a-4ee5-8b00-91029116f3d4 HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:44950 - "GET /api/groups/shopping/lists/0f4c6e3d-483a-4ee5-8b00-91029116f3d4 HTTP/1.1" 200 OK
mealie-dev   | INFO:     127.0.0.1:60898 - "GET /api/app/about HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:44950 - "GET /api/groups/shopping/lists/0f4c6e3d-483a-4ee5-8b00-91029116f3d4 HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:44950 - "GET /api/groups/shopping/lists/0f4c6e3d-483a-4ee5-8b00-91029116f3d4 HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:47518 - "GET /api/groups/shopping/lists/0f4c6e3d-483a-4ee5-8b00-91029116f3d4 HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:47518 - "GET /api/groups/shopping/lists/0f4c6e3d-483a-4ee5-8b00-91029116f3d4 HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:48388 - "GET /api/groups/shopping/lists/0f4c6e3d-483a-4ee5-8b00-91029116f3d4 HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:48388 - "GET /api/groups/shopping/lists/0f4c6e3d-483a-4ee5-8b00-91029116f3d4 HTTP/1.1" 200 OK
mealie-dev   | INFO:     127.0.0.1:47548 - "GET /api/app/about HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:48388 - "GET /api/groups/shopping/lists/0f4c6e3d-483a-4ee5-8b00-91029116f3d4 HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:48388 - "GET /api/groups/shopping/lists/0f4c6e3d-483a-4ee5-8b00-91029116f3d4 HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:48388 - "GET /api/groups/shopping/lists/0f4c6e3d-483a-4ee5-8b00-91029116f3d4 HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:48388 - "GET /api/groups/shopping/lists/0f4c6e3d-483a-4ee5-8b00-91029116f3d4 HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:48388 - "GET /api/groups/shopping/lists/0f4c6e3d-483a-4ee5-8b00-91029116f3d4 HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:48388 - "GET /api/groups/shopping/lists/0f4c6e3d-483a-4ee5-8b00-91029116f3d4 HTTP/1.1" 200 OK
mealie-dev   | INFO:     127.0.0.1:40026 - "GET /api/app/about HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:48388 - "GET /api/groups/shopping/lists/0f4c6e3d-483a-4ee5-8b00-91029116f3d4 HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:48388 - "GET /api/groups/shopping/lists/0f4c6e3d-483a-4ee5-8b00-91029116f3d4 HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:48388 - "GET /api/groups/shopping/lists/0f4c6e3d-483a-4ee5-8b00-91029116f3d4 HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:48388 - "GET /api/groups/shopping/lists/0f4c6e3d-483a-4ee5-8b00-91029116f3d4 HTTP/1.1" 200 OK
mealie-dev   | INFO:     127.0.0.1:46042 - "GET /api/app/about HTTP/1.1" 200 OK
mealie-dev   | INFO:     192.168.69.1:54606 - "GET /api/groups/shopping/lists/0f4c6e3d-483a-4ee5-8b00-91029116f3d4 HTTP/1.1" 200 OK
mealie-dev   | INFO:     127.0.0.1:45518 - "GET /api/app/about HTTP/1.1" 200 OK
mealie-dev   | INFO:     127.0.0.1:47886 - "GET /api/app/about HTTP/1.1" 200 OK
```

**Comment by boc-the-git** [comment]
On my phone I've just done a quick test..
Created a new shopping list, went to meal plan, added the day. 3 recipes linked.
Then I checked every ingredient on the list and deleted all.
Then I went to meal plan and added the day again, and only 2 recipes show as linked.

So I thought maybe it's the 2nd or later time you use a list that the problem occurs..

Created a new list to confirm and this time, the first time adding things to the list, only 2 recipes linked!

(at no point has the meal plan changed for any of these tests)

**Comment by michael-genson** [comment]
@boc-the-git can you see how it works now? I redid the implementation and it seems to work 100% of the time.
I also added a scale indicator - at some point I want this to actually be able to modify the scale in the dialog, but for now it's a reference only:
image

**Comment by boc-the-git** [comment]
@michael-genson I'd been away and then dealing with some higher priority stuff. I think I've got through all that now, so I plan to tackle this soon - worst case would be by mid next week.

I'm going to completely destroy my containers/data and see if I can reproduce on a clean setup. My hope is that I had some corrupted data that was causing this, given it was my Dev container.

**Comment by monksy** [comment]
I would love this from a point of view that you can do meal planning, you can get a partical understanding about what you need to prep, you can generate a report of the ingredients that you need, and you could output your macros/nutrician. I think that wouldd be pretty exciting.

**Comment by boc-the-git** [comment]
@michael-genson I can look to add more info if needed tomorrow, but I can confirm with a clean environment, the issue has recurred.
I created a clean environment, added the following 3 recipes, added them to my mealplan in the order Creme Brulle, Pad Thai, Beans, Pad Thai.. then added day to a shopping list (after creating it), and the shopping list is showing only 1 linked recipe.
I expect you could recreate it easily with those steps.
Note I'm using sqlite in this container, my prior tests were in postgres (so it's not db specific).

https://www.recipetineats.com/creme-brulee/
https://www.recipetineats.com/parmesan-roasted-green-beans/
https://www.recipetineats.com/chicken-pad-thai/

image

image

**Comment by michael-genson** [comment]
@boc-the-git I can't reproduce this at all - here is a gif of me following the exact steps that you described:
2023-11-12_09h51_31

Can you share anything you may have done differently? Your deployment details? @hay-kot - can you reproduce the issue?

**Comment by boc-the-git** [comment]
It doesn't look like I did anything different @michael-genson , except adding things to meal planner in the opposite order. Though I've tried the order you did, and I get the bad result again, not all recipes linked on the shopping list.

Keen to hear how Hayden might get on.. it's a strange one.
I'm no JS expert, is there some easy logging we can dump in there to see if it reveals anything?

Deployment is via docker-compose, with no material values changed from the file in the repo - just container name, baseurl, user/pass, etc. Caddy is my reverse proxy. Yml at bottom of this comment.

Side note, what tool are you using to record the gif? Would be keen to add it to my arsenal.

```Yml
       │ File: docker/docker-compose.yml
───────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ version: "3.4"
   2   │ services:
   3 ~ │   # db:
   4 ~ │   #   container_name: mealie-dev-db
   5 ~ │   #   image: postgres:15.4
   6 ~ │   #   environment:
   7 ~ │   #     POSTGRES_USER: mealie
   8 ~ │   #     POSTGRES_PASSWORD: mealie
   9 ~ │   #   volumes:
  10 ~ │   #     - postgres:/var/lib/postgresql/data
  11 ~ │   #   restart: unless-stopped
  12 ~ │
  13 ~ │   mealie-dev:
  14 ~ │     #    container_name: mealie-nightly
  15 ~ │     #    image: ghcr.io/mealie-recipes/mealie:nightly
  16 ~ │     container_name: mealie-dev
  17   │     image: mealie:dev
  18   │     build:
  19   │       context: ../
  20   │       target: production
  21   │       dockerfile: ./docker/Dockerfile
  22   │     restart: always
  23   │     volumes:
  24   │       - mealie-data:/app/data/
  25   │     ports:
  26   │       - 9091:9000
  27 + │       # depends_on:
  28 + │       # - db
  29   │     environment:
  30 + │       # Set Frontend ENV Variables Here
  31 + │       THEME_LIGHT_PRIMARY: #507B8F
  32 + │       THEME_LIGHT_ACCENT: #3B7064
  33 + │       THEME_DARK_PRIMARY: #507B8F
  34 + │       THEME_DARK_ACCENT: #3B7064
  35 + │       THEME_USE_DARK: "false"
  36 + │
  37 + │       DEFAULT_EMAIL: user
  38 + │       DEFAULT_PASSWORD: pass
  39 + │
  40   │       ALLOW_SIGNUP: "false"
  41   │
  42 + │       BASE_URL: https://redacted
  43 + │
  44 + │       # DB_ENGINE: postgres
  45   │       DB_ENGINE: sqlite # Optional: 'sqlite', 'postgres'
  46   │       # =====================================
  47   │       # Postgres Config
  48 ~ │       # POSTGRES_USER: mealie
  49 ~ │       # POSTGRES_PASSWORD: mealie
  50 ~ │       # POSTGRES_SERVER: db
  51 ~ │       # POSTGRES_PORT: 5432
  52 ~ │       # POSTGRES_DB: mealie
  53   │
  54   │       # =====================================
  55   │       # Web Concurrency
  56   │       WEB_GUNICORN: "false"
  57   │       WORKERS_PER_CORE: 0.5
  58   │       MAX_WORKERS: 1
  59   │       WEB_CONCURRENCY: 1
  60   │       # =====================================
  61   │       # Email Configuration
  62   │       # SMTP_HOST=
  63   │       # SMTP_PORT=587
  64   │       # SMTP_FROM_NAME=Mealie
  65   │       # SMTP_AUTH_STRATEGY=TLS # Options: 'TLS', 'SSL', 'NONE'
  66   │       # SMTP_FROM_EMAIL=
  67   │       # SMTP_USER=
  68   │       # SMTP_PASSWORD=
  69 + │       SMTP_HOST: redacted
  70 + │       SMTP_PORT: 8025
  71 + │       #- SMTP_USER=username
  72 + │       #- SMTP_PASSWORD=password
  73 + │       SMTP_FROM_NAME: Mealie
  74 + │       SMTP_FROM_EMAIL: redacted
  75 + │       SMTP_AUTH_STRATEGY: NONE
  76   │
  77   │ volumes:
  78   │   mealie-data:
  79   │     driver: local
  80 + │   # postgres:
  81 + │   #   driver: local
```

**Comment by michael-genson** [comment]
Hmmm, I've had issues building the container locally from the dev instance before, with it caching stuff it shouldn't be. Probably user error on my end. For development I always use the makefile (it also provides extra dev tools)

> what tool are you using to record the gif?

[Screenpresso](https://www.screenpresso.com/), I love it. Pretty sure it's only on Windows, though. It's free with some non-intrusive ads, but I bought it to support them.

**Comment by boc-the-git** [comment]
I'll get to testing it with the makefile ASAP - if it's quick and easy I might get it done tonight, but haven't done it before so will see how I go.

Thanks for the Screenpresso recommendation.

**Comment by boc-the-git** [comment]
@michael-genson I've done that testing now.. tested ~10 times with a different shopping list (but the same meal plan) each time.
The very first time I did the test, only 2/3 recipes ended up linked on the meal plan. All other times, 3/3 ended up linked, correctly.

I cleaned the data with `make clean-data`, and couldn't replicate the issue..

Bit stumped on this one.

**Comment by hay-kot** [comment]
I went through the testing process and it all worked as expected. I'm okay merging as is and getting user feedback on any issues that arise 👍

**Review by hay-kot — APPROVED** [review]

**Pull request merged**
