### PR TITLE
Meal Plan Improvements

### LINKED ISSUE #2256: [v1.0.0b] - Recipe ratings not showing on Meal Planner
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Recipe ratings are not showing properly on the Meal Planner

A rated recipe:

image

Ratings not populated in Meal Planner entry:

image

### Deployment

Docker (Linux)

### Deployment Details

Version: omni-nightly
Build: 8d79773bf65eb6bfd9021963324d53a25aab3cde

### LINKED ISSUE #2446: [nightly] - Meal Plan Notes allow Submission Without Title/Note Text, but Return 422
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

image

image

image

Planning to handle in #2399 but submitting since it may be a little while before I get to it.

### Deployment

Docker (Linux)

### Deployment Details

_No response_

### PR DESCRIPTION
**Pull request by Grygon**
## What type of PR is this?

- bug
- cleanup
- feature

## What this PR does / why we need it:

- Re-adds the ratings to recipes on the Meal Plan
- Adds horizontal scrolling to the meal plan, rather than letting elements warp
- Adds the ability to specify quantities to recipes that have been added to the meal plan
- Validates that note titles are populated

## Which issue(s) this PR fixes:
Fixes #2256
Fixed #2446

## Special notes for your reviewer:

N/A

## Testing

For frontend changes, tested manually and confirmed data displays appropriately now.

### Ratings
Visually verify stars are present.
image

### Scrolling
Resize window to a variety of sizes and verify that arrows are present in any non-mobile view, and they work as expected:
image

Note: There is no implementation for a Mobile view at this time, any attempts cluttered it up and didn't feel super necessary so I left it out.

### Quantities
Validate that the recipe indicates a quantity when it isn't 1.
image

Add Recipes to the Meal Plan in all possible workflows and verify that specified quantities populate:
image
image

Verify that the Edit page properly propagates quantities when modified
image

For backend changes, modified existing unit test and did additional validation via API calls.

## Release Notes

```release-note
Show ratings on the meal plan.
Meal plan scrolls to show days
Associate quantities with recipes on a meal plan
Perform validation on meal plan notes
```

### CODE REVIEW

**Comment by cguijt** [comment]
Just like I discussed on Discord; I'd like to see some other features to the mealplan as well;

- Would be great if the mealplan would also remember the last date-range you've selected when switching between pages.
- Adding the entire date selection, including the specified quantity per recipe, to a shopping list.

**Comment by Grygon** [comment]
Adding link to discussion requesting the bulk-add: https://github.com/hay-kot/mealie/discussions/1899

**Comment by hay-kot** [comment]
Hey! Thanks for the PR 

> Adds horizontal scrolling to the meal plan, rather than letting elements warp

I much prefer the current behavior. Can you remove that from this PR or submit a PR with the other improvements you've made here?

**Comment by Grygon** [comment]
@hay-kot Sure, will get on that in a sec!

Out of curiosity, what about the new layout do you find worse? I think there's definitely room to grow on my implementation, but it fixes this issue that seriously bugs me:

image

**Comment by seankhl** [comment]
In terms of meal plan view improvements, I think there could be a few interesting options for configuring days shown:
  - show current week (Sun-Sat or Mon-Sun depending on week starts option)
  - show `n` days starting from current day
  - show `m` days before and `n` days after current day (less immediately useful)

Also totally agree with fitting the full week onto one row!

**Review by Noko-Rammutla — APPROVED** [review]

**Comment by ulimanaio** [comment]
> In terms of meal plan view improvements, I think there could be a few interesting options for configuring days shown:
> 
> * show current week (Sun-Sat or Mon-Sun depending on week starts option)
> * show `n` days starting from current day
> * show `m` days before and `n` days after current day (less immediately useful)
> 
> Also totally agree with fitting the full week onto one row!

Is there a way to let the week start with Monday instead of Sunday?

**Comment by Bibz87** [comment]
> > In terms of meal plan view improvements, I think there could be a few interesting options for configuring days shown:
> > 
> > * show current week (Sun-Sat or Mon-Sun depending on week starts option)
> > * show `n` days starting from current day
> > * show `m` days before and `n` days after current day (less immediately useful)
> > 
> > Also totally agree with fitting the full week onto one row!
> 
> Is there a way to let the week start with Monday instead of Sunday?

First day of the week can already be set in Group settings.

**Pull request closed without merging**
