### PR TITLE
cleanup: Add constant SECONDS_IN_MINUTE in runner.py

### PR DESCRIPTION
**Pull request by ablazejuk**
## What type of PR is this?

_(REQUIRED)_

- cleanup

## What this PR does / why we need it:

Replace a magic number with a constant.

## Which issue(s) this PR fixes:

None

### CODE REVIEW

**Comment by boc-the-git** [comment]
Please edit your pull request and fill in the template

**Comment by ablazejuk** [comment]
> Please edit your pull request and fill in the template

Done

**Comment by michael-genson** [comment]
This seems superfluous, and you haven't really given us any reason to consider it, so we've decided to close it. In the future, please have a clear motivation/use-case before opening a pull request for review.

**Comment by ablazejuk** [comment]
> This seems superfluous, and you haven't really given us any reason to consider it, so we've decided to close it. In the future, please have a clear motivation/use-case before opening a pull request for review.

"In general it is a bad idea to have raw numbers in your code. You should hide them behind well-named constants.", Clean Code, Robert C. Martin.

Here is your motivation.

**Pull request closed without merging**
