### PR TITLE
fix: running the container with PUID=0 and PGID=0

### PR DESCRIPTION
**Pull request by xThaid**
## What type of PR is this?

_(REQUIRED)_

- bug

## What this PR does / why we need it:

_(REQUIRED)_

I run the container with PUID=0 and PGID=0 and when updated to the recent release (V1.0.0), it couldn't start. I was getting a stream of logs like:
```
Switching to dedicated user
usermod: no changes
Switching to dedicated user
usermod: no changes
Switching to dedicated user
usermod: no changes
Switching to dedicated user
usermod: no changes
Switching to dedicated user
...
```
It is because the entrypoint script (running with id=0) tries to create a new user (with id=0) and then executes itself again as that user. Hence the infinite loop.

## Which issue(s) this PR fixes:
Regression caused by #2882 

_(REQUIRED)_

## Testing
Build the container and run it with PUID=0 and PGID=0

### CODE REVIEW

**Comment by hay-kot** [comment]
Thanks for the PR! Why do you want to run as 0?

**Comment by xThaid** [comment]
I use rootless Podman to run containers, so there's no need to change the user ID further.

**Comment by renhardy** [comment]
My setup also requires having PUID=0 and PGID=0. This change would be appreciated.

**Review by renhardy — APPROVED** [review]

**Review by hay-kot — APPROVED** [review]
Tested locally, LGTM

**Pull request merged**
