### PR TITLE
Fix user login and creation with LDAP

### LINKED ISSUE #1774: [v1.0.0b] - Missing libldap_r-2.4.so.2 library for LDAP
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

When using LDAP as authentication method, the following error is given in the log:

`ImportError: libldap_r-2.4.so.2: cannot open shared object file: No such file or directory
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 43, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 75, in __call__
    raise exc
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 231, in app
    raw_response = await run_endpoint_function(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/app/./mealie/routes/auth/auth.py", line 58, in get_token
    user = authenticate_user(session, email, password)  # type: ignore
  File "/app/./mealie/core/security/security.py", line 120, in authenticate_user
    return user_from_ldap(db, email, password)
  File "/app/./mealie/core/security/security.py", line 51, in user_from_ldap
    import ldap
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/ldap/__init__.py", line 34, in <module>
    import _ldap
ImportError: libldap_r-2.4.so.2: cannot open shared object file: No such file or directory`

Due to the error, LDAP authentication always leads to an error and makes it impossible to login. 

The problem seems to be that the package _libldap-2.4-2_ is missing.

After installing the package using the following command, the issue is resolved:
`apt-get update && apt-get install -y libldap-2.4-2`

_Unfortunately, due to additional bugs within the LDAP authentication, it is still not possible to login after the change. I will create a separate bug report for those, since they are code based._ 

### Deployment

Docker (Linux)

### Deployment Details

Docker install using a portainer stack on an unraid system.

### LINKED ISSUE #1832: [v1.0.0b] - API uses invalid LDAP query
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

In short, it does not appear that the backend LDAP query supports my current LDAP configuration. As you can see, the LDAP log shows a query using objectClass=user and cn=tnunamak, but I do not use this objectClass and I use uid instead of cn. FWIW, I was able to get it working with 0.5.

API configuration:
```
LDAP_AUTH_ENABLED: "true"
LDAP_SERVER_URL: "ldap://ldap.my.domain"
LDAP_TLS_INSECURE: "true"
LDAP_BIND_TEMPLATE: uid={},ou=People,dc=my,dc=domain
LDAP_BASE_DN: dc=my,dc=domain
LDAP_ADMIN_FILTER: (memberOf=cn=Admins,dc=my,dc=domain)
```

LDAP log:
```
6373df5e conn=12748 op=0 BIND dn="uid=tnunamak,ou=People,dc=my,dc=domain" method=128
6373df5e conn=12748 op=0 BIND dn="uid=tnunamak,ou=People,dc=my,dc=domain" mech=SIMPLE ssf=0
6373df5e conn=12748 op=0 RESULT tag=97 err=0 text=
6373df5e conn=12748 op=1 SRCH base="dc=my,dc=domain" scope=2 deref=0 filter="(&(?objectClass=user)(|(cn=tnunamak)(?sAMAccountName=tnunamak)(mail=tnunamak)))"
6373df5e conn=12748 op=1 SRCH attr=name mail
6373df5e conn=12748 op=1 SEARCH RESULT tag=101 err=32 nentries=0 text=
```

LDAP user:
image
image
image
image

### Deployment

Docker (Linux)

### Deployment Details

beta-5

### LINKED ISSUE #2059: [v1.0.0b] - Ldap Authentication IndexError
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Using the nightly docker api image (f7ba5690057b), the api is throwing the following error, when trying to use ldap for authentication:

```
 File "/app/./mealie/routes/auth/auth.py", line 57, in get_token
    user = authenticate_user(session, email, password)  # type: ignore
  File "/app/./mealie/core/security/security.py", line 120, in authenticate_user
    return user_from_ldap(db, email, password)
  File "/app/./mealie/core/security/security.py", line 89, in user_from_ldap
    if user_entry is not None and len(user_entry[0]) != 0 and user_entry[0][0] is not None:
IndexError: list index out of range
```

I'm using Authentik for ldap and confirmed that my setup is working via:

```
ldapsearch -h ldap_server -p 1234 -D "cn=username,dc=domain,dc=de" -W -b "cn=username,ou=users,dc=domain,dc=de" "name" "mail"
```

My corresponding docker env vars:
```
LDAP_BIND_TEMPLATE: "cn={},dc=domain,dc=de"
LDAP_BASE_DN: "cn={},ou=users,dc=domain,dc=de"
```

### Deployment

Docker (Linux)

### Deployment Details

_No response_

### PR DESCRIPTION
**Pull request by cmintey**
## What type of PR is this?

- bug
- documentation
- feature

## What this PR does / why we need it:

This change builds off of the great work done by @ERLKDev in #1777, which appears to be dead.

The LDAP flow was changed to the following:
1. bind to the LDAP server using an external user (one that has search privileges)
2. search for users given the `LDAP_USER_FILTER`. By doing this, we make no assumptions as to the query structure
3. try to bind with the user_dn returned in step 2 and the provided password
4. check if a user with the username or email already exists
5. otherwise, create a new user

This PR will require new environment variables which have been documented as well.

## Which issue(s) this PR fixes:

Fixes #2059 
Fixes #1175
Fixes #1774
Fixes #1832

## Testing

Unit tests were created in the original PR, they have been updated and pass as expected.

## Release Notes

```release-note
Fixes LDAP user login and creation. Please check the new environment variables required for LDAP (https://nightly.mealie.io/documentation/getting-started/installation/backend-config/#ldap)
```

### CODE REVIEW

**Comment by hay-kot** [comment]
This looks excellent. Thanks so much for getting this over the finish line! 

I've been looking at implement some E2E testing with https://glauth.github.io/ in a github action. Would love to get your thoughts on that if you have any.

**Comment by proffalken** [comment]
> This looks excellent. Thanks so much for getting this over the finish line!
> 
> I've been looking at implement some E2E testing with https://glauth.github.io/ in a github action. Would love to get your thoughts on that if you have any.

FWIW I'm currently running https://github.com/nitnelave/lldap on my home network, but given that I've now got [Unifi ID](https://ui.com/uid) installed on my cloudkey for my home network, I'm going to have a go at setting that up as well.

**Comment by cmintey** [comment]
> This looks excellent. Thanks so much for getting this over the finish line!
> 
> I've been looking at implement some E2E testing with https://glauth.github.io/ in a github action. Would love to get your thoughts on that if you have any.

I had a look at GLAuth and it seems like it would do well for e2e testing in github. You could even test out multiple configurations easily (see: https://github.com/glauth/glauth/blob/master/v2/sample-simple.cfg#L41-L45). I could assist in configuration if needed.

> FWIW I'm currently running https://github.com/nitnelave/lldap on my home network, but given that I've now got [Unifi ID](https://ui.com/uid) installed on my cloudkey for my home network, I'm going to have a go at setting that up as well.

I'm also running lldap, which is great. Would be interested to see how well this integrates with the Unifi ID...

**Comment by Zackptg5** [comment]
I've been testing this out and overall working great. One issue though, it appears that mealie still uses it's own database, only pulling from lldap when user doesn't exist in its database. 
Is there a way to use lldap exclusively? For example, when new user is created/deleted in mealie, it's also created/deleted in lldap server. If logging in and user deleted from lldap, mealie will delete it on next login attempt or just not use its own user section at all.
In it's current iteration, mealie will default to it's own database over lldap which can get messy quick. If a user is created in mealie, it won't be added to lldap. If user is deleted in lldap, it won't be deleted in mealie.
It'd be better if ldap is enabled, mealie will use it exclusively for all users. This way I could just use lldap server for all user management for mealie and other services that pull from it

**Comment by cmintey** [comment]
Yeah, I realized this problem as well and didn’t catch it in my testing. I have a proposed solution in this discussion #2126. Just need to get thoughts on if this is the right way to proceed.

I personally think having an admin set the login method (ldap or mealie) for each user would be better than just deleting the user entry if they log in with ldap for the first time.

I also don’t think that mealie should be managing user creation/deletion on your ldap server. If you need to add or remove a user, that should be done in the ldap server itself

**Comment by Zackptg5** [comment]
@cmintey exactly what I was thinking. If using ldap, all user/group management should be done there. It would be cool for mealie user/group management page to be able to manage that but I don't know how much extra complexity that would be

**Pull request merged**
