### PR TITLE
Docker/run as nonroot

### LINKED ISSUE #657: Container running as root user
I have tried to deploy with:
securityContext:
  runAsNonRoot: true

this has resulted into groupmode error

**Expected behavior**
Container and application should run fine.

**Actual Behavior**
container fails with following error:
Production
groupmod: Permission denied.
groupmod: cannot lock /etc/group; try again later.

**Device Information (please complete the following information):**
 - OS: Ubuntu 20.04
 - Deployment: Microk8s

### PR DESCRIPTION
**Pull request by usma0118**
Fixes #657 

- [x] Modified to run docker image as user mealie (PUID: 911, PGID: 911)
- [x] removed groupmod from run script and handled in docker file.
- [x] Bumped image to python:3.9.6
- [x] moved scheduler.db to /app/temp as no exposed volume, Thanks to @articuno1au
- [x] bumped poetry version.
- [x] Changed caddy port from env variable App_Port (default 80) for non-root binding.
- [x] Docker port defaults to 9080
- [x] app file permissions are set in docker image.

### CODE REVIEW

**Comment by usma0118** [comment]
I have done vulnerability scanning in docker and bumped certain versions.

only remaining one is apprise:
image

**Comment by hay-kot** [comment]
Everything looks good to me. If you can, I would appreciate it if you could add some documentation in the installation instructions on the new parameters you've added as well as any steps required to run as non-root.

**Comment by usma0118** [comment]
Sure, i will update docs with necessary info.

**Comment by articuno1au** [comment]
That's a ton of work @usma0118, sorry I didn't contribute at all to the additional stuff.

The docker port change is nicely done too. I'll pull this branch and let you know how it goes.

Thanks for all the effort :1st_place_medal:

**Comment by articuno1au** [comment]
I ran into a problem attempting to build the container.

To check it out, I ran `git fetch origin refs/pull/692/head:local-test` to move the PR to a local testing branch.

Running docker build, I end up with a dependancy error in poetry
```
Creating virtualenv mealie in /opt/pysetup/.venv
Installing dependencies from lock file
Warning: The lock file is not up to date with the latest changes in pyproject.toml. You may be getting outdated dependencies. Run update to update them.

  SolverProblemError

  Because mealie depends on lxml (4.6.3) which doesn't match any versions, version solving failed.

  at /opt/poetry/venv/lib/python3.9/site-packages/poetry/puzzle/solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes
The command '/bin/sh -c poetry install -E pgsql --no-dev' returned a non-zero code: 1
```
It might be something I'm doing wrong, but just wanted to call it out.

**Comment by usma0118** [comment]
@hay-kot i have updated documentation. you may proceed with PR.

**Comment by usma0118** [comment]
your dev environment is not properly setup. 
run poetry update in you evn/venv.

> I ran into a problem attempting to build the container.
> 
> To check it out, I ran `git fetch origin refs/pull/692/head:local-test` to move the PR to a local testing branch.
> 
> Running docker build, I end up with a dependancy error in poetry
> 
> ```
> Creating virtualenv mealie in /opt/pysetup/.venv
> Installing dependencies from lock file
> Warning: The lock file is not up to date with the latest changes in pyproject.toml. You may be getting outdated dependencies. Run update to update them.
> 
>   SolverProblemError
> 
>   Because mealie depends on lxml (4.6.3) which doesn't match any versions, version solving failed.
> 
>   at /opt/poetry/venv/lib/python3.9/site-packages/poetry/puzzle/solver.py:241 in _solve
>       237│             packages = result.packages
>       238│         except OverrideNeeded as e:
>       239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
>       240│         except SolveFailure as e:
>     → 241│             raise SolverProblemError(e)
>       242│
>       243│         results = dict(
>       244│             depth_first_search(
>       245│                 PackageNode(self._package, packages), aggregate_package_nodes
> The command '/bin/sh -c poetry install -E pgsql --no-dev' returned a non-zero code: 1
> ```
> 
> It might be something I'm doing wrong, but just wanted to call it out.

**Comment by articuno1au** [comment]
Apologies if I'm misunderstanding, isn't the Poetry context/venv inside the container?

```
Step 15/56 : ENV POETRY_VERSION=1.1.7
 ---> Using cache
 ---> dc319cdf5110
Step 16/56 : RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
 ---> Using cache
 ---> 0436f19eafd0
Step 17/56 : WORKDIR $PYSETUP_PATH
 ---> Using cache
 ---> 0a05848cf21f
Step 18/56 : COPY ./poetry.lock ./pyproject.toml ./
 ---> Using cache
 ---> 2d88f8894ce8
Step 19/56 : RUN poetry install -E pgsql --no-dev
 ---> Running in cf71570615cc
Creating virtualenv mealie in /opt/pysetup/.venv
Installing dependencies from lock file
Warning: The lock file is not up to date with the latest changes in pyproject.toml. You may be getting outdated dependencies. Run update to update them.

  SolverProblemError (and so the error continues)
  ```
So isn't that something we need to fix inside the container?

If I added the `poetry update` step between build phases (whenever we change poetry contexts), the container builds successfully (albeit slower). Changes are below
```
diff --git a/Dockerfile b/Dockerfile
index 6f063ca..b27a7d0 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -62,10 +62,13 @@ RUN apt-get update \
 ENV POETRY_VERSION=1.1.7
 RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -

+
 # copy project requirement files here to ensure they will be cached.
 WORKDIR $PYSETUP_PATH
 COPY ./poetry.lock ./pyproject.toml ./

+RUN poetry update
+
 # install runtime deps - uses $POETRY_VIRTUALENVS_IN_PROJECT internally
 RUN poetry install -E pgsql --no-dev

@@ -88,7 +91,7 @@ COPY ./poetry.lock ./pyproject.toml $MEALIE_HOME/

 # venv already has runtime deps installed we get a quicker install
 WORKDIR $MEALIE_HOME
-RUN . $VENV_PATH/bin/activate && poetry install
+RUN . $VENV_PATH/bin/activate && poetry update && poetry install
 WORKDIR /

 RUN chmod +x $MEALIE_HOME/mealie/run.sh
@@ -125,7 +128,7 @@ COPY ./gunicorn_conf.py $MEALIE_HOME

 # venv already has runtime deps installed we get a quicker install
 WORKDIR $MEALIE_HOME
-RUN . $VENV_PATH/bin/activate && poetry install -E pgsql --no-dev
+RUN . $VENV_PATH/bin/activate && poetry update && poetry install -E pgsql --no-dev
 WORKDIR /

 # copy frontend
```
Again, apologies if I'm misunderstanding here.

**Comment by usma0118** [comment]
Fair point, This should be fixed.
I will see if i can find sometime next week. otherwise why not create a PR for this change? :)

> Apologies if I'm misunderstanding, isn't the Poetry context/venv inside the container?
> 
> ```
> Step 15/56 : ENV POETRY_VERSION=1.1.7
>  ---> Using cache
>  ---> dc319cdf5110
> Step 16/56 : RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
>  ---> Using cache
>  ---> 0436f19eafd0
> Step 17/56 : WORKDIR $PYSETUP_PATH
>  ---> Using cache
>  ---> 0a05848cf21f
> Step 18/56 : COPY ./poetry.lock ./pyproject.toml ./
>  ---> Using cache
>  ---> 2d88f8894ce8
> Step 19/56 : RUN poetry install -E pgsql --no-dev
>  ---> Running in cf71570615cc
> Creating virtualenv mealie in /opt/pysetup/.venv
> Installing dependencies from lock file
> Warning: The lock file is not up to date with the latest changes in pyproject.toml. You may be getting outdated dependencies. Run update to update them.
> 
>   SolverProblemError (and so the error continues)
> ```
> 
> So isn't that something we need to fix inside the container?
> 
> If I added the `poetry update` step between build phases (whenever we change poetry contexts), the container builds successfully (albeit slower). Changes are below
> 
> ```
> diff --git a/Dockerfile b/Dockerfile
> index 6f063ca..b27a7d0 100644
> --- a/Dockerfile
> +++ b/Dockerfile
> @@ -62,10 +62,13 @@ RUN apt-get update \
>  ENV POETRY_VERSION=1.1.7
>  RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
> 
> +
>  # copy project requirement files here to ensure they will be cached.
>  WORKDIR $PYSETUP_PATH
>  COPY ./poetry.lock ./pyproject.toml ./
> 
> +RUN poetry update
> +
>  # install runtime deps - uses $POETRY_VIRTUALENVS_IN_PROJECT internally
>  RUN poetry install -E pgsql --no-dev
> 
> @@ -88,7 +91,7 @@ COPY ./poetry.lock ./pyproject.toml $MEALIE_HOME/
> 
>  # venv already has runtime deps installed we get a quicker install
>  WORKDIR $MEALIE_HOME
> -RUN . $VENV_PATH/bin/activate && poetry install
> +RUN . $VENV_PATH/bin/activate && poetry update && poetry install
>  WORKDIR /
> 
>  RUN chmod +x $MEALIE_HOME/mealie/run.sh
> @@ -125,7 +128,7 @@ COPY ./gunicorn_conf.py $MEALIE_HOME
> 
>  # venv already has runtime deps installed we get a quicker install
>  WORKDIR $MEALIE_HOME
> -RUN . $VENV_PATH/bin/activate && poetry install -E pgsql --no-dev
> +RUN . $VENV_PATH/bin/activate && poetry update && poetry install -E pgsql --no-dev
>  WORKDIR /
> 
>  # copy frontend
> ```
> 
> Again, apologies if I'm misunderstanding here.

**Comment by articuno1au** [comment]
@usma0118 @hay-kot  - I've forked the repo so I could make the change as suggested, however I've run into a problem.

- If the container is run with PUID/PGID 911 and the files on the filesystem are set to be owned by 911, everything works fine.
- If the container is run with PUID/PGID 1000 and the files on the filesystem are owned by 911, everything works fine
- If the container is run with PUID/PGID 1000 and the files on the filesystem are owned by 1000, the container won't start with a file permission failure

I modified the Dockerfile to start with a default PUID/PGID of 1000, and it's able to access the filesystem. So the goal of not running as root is achieved, however we're now hardlocked into a PUID/PGID of 911.

I think the problem is that we're attempting to make the permissions changes as part of the build process as opposed to doing it with a script at runtime. Basically, 911 is being used when building the image, and the filesystem inside the container is owned by it at runtime
image
I think we need to handle chmod/chown calls at runtime, not during the build process.

I'm throwing my notes here because I'm about to run out of time to keep working this, but I'm currently rebuilding the image with the permissions changes in run.sh to see how that goes.

**Comment by articuno1au** [comment]
Prior art: https://github.com/linuxserver/docker-openssh-server/blob/b222249f3be625ec2b4d4762bb4dc0113707d046/root/etc/cont-init.d/10-adduser

**Comment by hay-kot** [comment]
I've reverted this PR since it put the dev branch in an unusable state given @articuno1au comments and failing tests in the CI/CD pipeline. 

Looks like some additional work needs to be done with permission setting at runtime.

**Pull request merged**
