### PR TITLE
feat: Offline Shopping List

### LINKED ISSUE #3718: Shopping list goes blank as soon as internet connection is lost on iPhone
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

When I have a shopping list open on my iPhone, it goes blank as soon as the iPhone loses it's internet connection.

### Steps to Reproduce

1. Create a shopping list
2. Open the list on iPhone
3. Set iPhone to airplane mode, be sure to also turn off WiFi
4. Shopping list goes blank

### Please provide relevant logs

```
INFO     2024-06-08T19:33:28 - [172.30.0.1:55372] 200 OK "GET /api/groups/shopping/lists/92893449-4706-4999-bacb-9c74c5b58d85 HTTP/1.1"
INFO     2024-06-08T19:33:23 - [172.30.0.1:55372] 200 OK "GET /api/groups/shopping/lists/92893449-4706-4999-bacb-9c74c5b58d85 HTTP/1.1"
INFO     2024-06-08T19:33:18 - [172.30.0.1:55372] 200 OK "GET /api/groups/shopping/lists/92893449-4706-4999-bacb-9c74c5b58d85 HTTP/1.1"
INFO     2024-06-08T19:33:18 - [172.30.0.1:55374] 200 OK "GET /api/groups/labels?page=1&perPage=-1 HTTP/1.1"
INFO     2024-06-08T19:33:17 - [172.30.0.1:55372] 200 OK "GET /api/groups/shopping/lists?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1"
```
At 19:33 I put my phone on airplane mode. After that, the server just didn't get any requests anymore. There's nothing special to be seen in the server logs as far as I can see.

### Mealie Version

- Docker: `ghcr.io/mealie-recipes/mealie:latest` which comes down to 1.8.0 at the time I write this image.
- Build: [583bd742fb7bbeee0191a6e6601677df57d86a11](https://github.com/mealie-recipes/mealie/commit/583bd742fb7bbeee0191a6e6601677df57d86a11)

### Deployment

Docker (Synology)

### Additional Deployment Details

I used the Postgres Docker compose file.

### PR DESCRIPTION
**Pull request by michael-genson**
## What type of PR is this?

_(REQUIRED)_

- feature

## What this PR does / why we need it:

_(REQUIRED)_

This PR lets the shopping list work while offline. It does this by queueing requests, mirroring them locally, then sending them to the server whenever we can. There are a few caveats:
- The user needs to first open the shopping list while they have connection. We're not prefetching the list before the user navigates to it. Once they've successfully fetched the list, they can lose connection
- The local changes are only sent to the server if the user connects to the server while the shopping list is open. At that point all changes are sent to the server. There is no background task that does this automatically (e.g. if the user closes the app, more on this below)
- If a user makes changes offline, and someone else makes changes online, and the user fails to reach the server within 5 minutes, their changes are considered "expired" and will be ignored (more on this below)

A few changes were made to get this to work:
- The polling timeout has been increased to 24 hours. We don't know how long the user is going to be offline, but 24 hours is more than reasonable. We already disable requests if the user is idle, so we're still safe from bombarding the server with bad requests
- Previously, there was a backend-triggered "Item Deleted Successfully" message upon item deletion. Since deletions are queued and sent later, this message doesn't really make sense anymore, so I got rid of it
- To track state/reactivity, new items can accept an id from the frontend (so now the frontend generates a UUID before the item is even created on the backend)

Since not everything works offline (adding/removing recipes, changing the owner, etc.) we disable some features when we detect a network error (which will happen any time an item is created/updated/deleted, or during the normal 5 second polling period where we fetch the new list). I also added a warning banner letting the user know they're offline:

image

## Which issue(s) this PR fixes:

_(REQUIRED)_

Fixes https://github.com/mealie-recipes/mealie/issues/3718

## Special notes for your reviewer:

_(fill-in or delete this section)_

One implementation detail I simplified was the queue timeout. I mentioned that if the offline queue is too far behind the server (i.e. someone made changes a while ago) we just dump the queue. Ideally, we compare the timestamp of each item on the server, and only dump items with conflicts (e.g. if the offline user edits an item that an online user edited, dump that, but if the offline user edited an item that the online user _didn't_ edit, keep that). However, this would be a lot more complex to implement (and probably be rather slow with large requests), and would probably only affect a handful of users. If this feature is requested later down the line we can consider adding it, but for now I think the existing behavior is fine.

I mentioned that updates are only sent to the server if the user is viewing the shopping list while online, and there is no background processing. PWAs do support this kind of background task using service workers, [including using our nuxtjs PWA](https://pwa.nuxtjs.org/workbox/), (which fires even if the user isn't using the app), but hell if I can figure out how to get that to work.

## Testing

_(fill-in or delete this section)_

Constantly testing the frontend online and offline. The online experience is unaffected (even though it's very different under the hood), aside from being a little more reactive (which is a nice plus).

### CODE REVIEW

**Comment by michael-genson** [comment]
For reviewers: in case you don't know, the Chrome dev console lets your throttle the network (including turning it off).
Dev Console -> Network Tab
image

I strongly recommend anyone reviewing this to play around with the shopping list both online and offline, to try to find bugs. I found a bunch during development (which have been fixed)

**Comment by boc-the-git** [comment]
The things noted under `Special notes for your reviewer`, I think those are all reasonable decisions given we are already talking about a < 5% scenario (assumption) of the shopping list being used whilst offline, and they become edge cases within that 5%.

**Comment by boc-the-git** [comment]
All the code LGTM. I just want to do a bit more playing around with it before approving.

**Review by boc-the-git — APPROVED** [review]
🚀

**Comment by bartkummel** [comment]
Awesome, I didn't expect this to be fixed this fast, when I wrote #3718. I understand very well that things like these are quite complex. Thank you so much @michael-genson !

One remark, I saw the statement about this being a "< 5% scenario". While that might be true, fixing this makes a HUGE difference for all users that experience this. In this case "< 5%" doesn't mean that every user will experience this in 5% of the cases, but more like 5% of the users experience this all the time. So, in my case for example, it makes the difference of whether or not I can switch to Mealie (from Paprika), because without offline usage of the shopping list, I simply can't use it. My supermarket is on the ground floor of a larger complex. There's only a little bit of mobile data reception close to the entrance. The shop does offer WiFi, but that only works less than 50% of the time and also doesn't cover the entire shop.

Well, that's a very long message to just say how grateful I am. 😉 I can't wait until the upcoming release!

**Comment by boc-the-git** [comment]
> Awesome, I didn't expect this to be fixed this fast, when I wrote https://github.com/mealie-recipes/mealie/issues/3718. I understand very well that things like these are quite complex.

Michael being Michael 🤷 

If you want to jump over to nightly @bartkummel you can use it immediately and give us first hand, real world feedback!

**Comment by bartkummel** [comment]
@boc-the-git I'll see if I can squeeze some time out of my busy calendar this weekend.

**Comment by michael-genson** [comment]
> There's only a little bit of mobile data reception close to the entrance

This was definitely the use case I was thinking of with this. It's not a true offline shopping list experience (see the caveats section on the PR: you need internet connection to establish the list, and you need to have the app open to send your changes after you regain connection) but it lets you work more-or-less seamlessly on a crappy connection.

If you run into any sync issues (or other issues) let us know. The shopping list gets used a lot, but I have no idea how many people will test out the offline features (and of those that do, how many will report issues)

**Comment by bartkummel** [comment]
I installed the nightly and found a bug. Here's what I did:
- Got to the shopping list on movile
- Set phone to airplane mode
- Check off 2 items while offline
- Disable airplane mode again

So far it works okay. The checked-off items are successfully synced with the backend. (I verified that by opening the same shopping list on my laptop.)
- But now I can't check off anything anymore. When I check it off, it briefly disappears, but then re-appears unchecked. See video
- This also happens on my laptop now.
- Navigating away from the shopping list on both devices and then reopening it doesn't solve it.
- Restarting Mealie (the backend) also doesn't solve it.

https://github.com/mealie-recipes/mealie/assets/20771942/7b268ec1-2f8e-438d-9b95-1cd36093a921

Is reporting here okay? Or wold you rather have an official bug report?

**Comment by boc-the-git** [comment]
> I installed the nightly and found a bug. Here's what I did:
> - Got to the shopping list on movile
> - Set phone to airplane mode
> - Check off 2 items while offline
> - Disable airplane mode again
> 
> So far it works okay. The checked-off items are successfully synced with the backend. (I verified that by opening the same shopping list on my laptop.)
> - But now I can't check off anything anymore. When I check it off, it briefly disappears, but then re-appears unchecked. See video
> - This also happens on my laptop now.
> - Navigating away from the shopping list on both devices and then reopening it doesn't solve it.
> - Restarting Mealie (the backend) also doesn't solve it.
> 
> https://github.com/mealie-recipes/mealie/assets/20771942/7b268ec1-2f8e-438d-9b95-1cd36093a921
> 
> Is reporting here okay? Or wold you rather have an official bug report?

We'll probably want to get that on a new issue I think, just for tracking purposes. Is there anything in the logs?
Cc @michael-genson

**Comment by michael-genson** [comment]
Well that was fast. Yeah a new issue is preferred. Grab your Mealie logs, your browser logs, and if you could snag the shopping list queue from your app data (in the browser) that'd be great

**Comment by bartkummel** [comment]
Sorry, I was very busy and didn't have time to create a proper ticket. However, I see that some follow up PRs have been merged already. I tested the latest nightly just now and it seems to work quite robust now! 👍🏻

**Comment by michael-genson** [comment]
All good! Appreciate the initial report :)

Since the latest nightly fixes the issue I'm sure it's the same one, but just to confirm: what timezone do you have your Mealie instance set to? Is it positive?

**Comment by bartkummel** [comment]
Yes, my timezone is `Europe/Amsterdam`, so that's `UTC+2` during summer. (`UTC+1` during winter.)

**Comment by michael-genson** [comment]
Yup, same issue then! I develop in UTC and then my instance is Chicago (which is -5 or -6) so I never caught the bug

**Pull request merged**
