### PR TITLE
feat: Data Management from Shopping List

### PR DESCRIPTION
**Pull request by michael-genson**
## What type of PR is this?

_(REQUIRED)_

- bug
- feature

## What this PR does / why we need it:

_(REQUIRED)_

This PR enables managing data from a shopping list. Namely:
1. Foods and units can be created from the shopping list (similar to how they can be created from recipes)
2. Food labels can be changed if the shopping list item uses a different label than the food

This also fixes a visual bug when creating new foods/units on recipes by force-closing the dropdown.

Creating foods from the shopping list (with fixed visual bug):
2024-05-15_11h27_50

Assigning label to food (note that other instances of "apple" are not updated because those items are already set to produce):
2024-05-15_11h28_28

(not pictured: the food "apple" is now re-labeled as "Juice")

## Which issue(s) this PR fixes:

_(REQUIRED)_

Closes https://github.com/mealie-recipes/mealie/discussions/3602

## Testing

_(fill-in or delete this section)_

Manually

### CODE REVIEW

**Review by boc-the-git — CHANGES_REQUESTED** [review]
Quite a few linter issues on this one @michael-genson

**Review by boc-the-git — COMMENTED** [review]
I'm effectively happy to approve this, bar the linting issues previously mentioned and ..

The "Copy to Food" functionality. I like it, but I wonder it it's going to not be clear to a user what it's actually doing? Particularly for say the 2nd and 3rd user of a system, not the "power user".. Thoughts? Wondering if there's an alternate wording, maybe something like "Permanently add Label to Food" (..but not exactly that)

**Comment by michael-genson** [comment]
Yeah I couldn't come up with anything concise enough other than "Copy to Food". Some others:
- Assign to Food
- Apply Label to Food
- Update Food Data
- Change Food Label
- Change Food Data Label
- Move Food to Label

I was avoiding "permanently" because it seems like a bulky word here, but that could work too. Also maybe adding a tooltip can work?

**Comment by Kuchenpirat** [comment]
I would suggest going for something shorter like `Label Food` or `Add Label`

I think you kinda don't need to reference Food since this is the toggled option. But a tooltip might be a nice middleground, but are not that practical on mobile.

**Comment by michael-genson** [comment]
Maybe "Set Label" or "Apply Label"? Or "Save Label"? I agree with dropping Food. It's more than "Add" because a Food might already have a Label, just a different one.

**Comment by michael-genson** [comment]
Updated to "Save Label":
image

**Review by boc-the-git — APPROVED** [review]

**Pull request merged**
