### PR TITLE
feat: Shopping list UI overhaul - increase list item width

### PR DESCRIPTION
**Pull request by Wetzel402**
## What type of PR is this?

- feature

## What this PR does / why we need it:

- A fix for long list item names

## Which issue(s) this PR fixes:

https://github.com/mealie-recipes/mealie/pull/4077
https://github.com/mealie-recipes/mealie/pull/4237
#4241 

## Testing

Tested in dev container

### CODE REVIEW

**Comment by Wetzel402** [comment]
In testing these are the maximum widths that do not push buttons off the screen.

**Review by Kuchenpirat — CHANGES_REQUESTED** [review]
I have it still doing wonky stuff on a screen with normal phone dimensions (Pixel 8)

image

**Comment by Wetzel402** [comment]
> I have it still doing wonky stuff on a screen with normal phone dimensions (Pixel 8)
> 
> image

Looks like this one is going to take more work and a possible rethink of the shopping list item.  I'm going to close this for now and try to work on it some more... Thanks!

**Comment by Kuchenpirat** [comment]
yeah, i think going with fixed column widths might not be the way to do this 👍

**Pull request closed without merging**
