### PR TITLE
Group based notification

### LINKED ISSUE #833: [v1.0.0b] [Task] - Group Based Event Notifications
### What is the problem this task addresses?

Currently, notifications are based around the administrator views. This doesn't provide much utility for individual groups. The notifications section should be migrated to a group based implementation.   

### Proposed/Possible Solution(s)?

To Complete This Task

- [x] Update Database Entries to have a relationship to a group.
- [x] Create a new card/page for managing notifications in the frontend. 
- [x] Ensure that server events that are dispatched only call handlers that are registered for the group.   

### Update:

See Comments 👇

### PR DESCRIPTION
**Pull request by Miroito**
Contributing to issue #833 

Draft for tracking advancements

### CODE REVIEW

**Comment by hay-kot** [comment]
You've got the basic idea. Two things,

1. Messages should container more specific information, in this case, they should provide a URL to the created recipe, and in the case of delete it should provide the name. 
2. Messages should be translatable

**Comment by Miroito** [comment]
Thanks for the feedback I will work on that!

**Comment by Miroito** [comment]
I did not mean to commit the url being falsely data.org_url. I will change it later.
edit: Looks like the CI failed for this exact reason as well.

**Comment by Miroito** [comment]
I have tackled all the low hanging fruits. Some of the other events may need a little bit more time for me to figure out and not miss anything.

**Comment by hay-kot** [comment]
Captured the following PR with a few modifications

- https://github.com/hay-kot/mealie/pull/1234

Thanks for all the work on this! 🚀

**Pull request closed without merging**
