### PR TITLE
feat: Added images to PWA shortcuts

### PR DESCRIPTION
**Pull request by Choromanski**
## What type of PR is this?

- bug
- feature

## What this PR does / why we need it:

It adds icons to the PWA shortcuts, currently on android the shortcuts have a white square next to them. This adds icons that match the menu bar.

Before

## Which issue(s) this PR fixes:

None

## Special notes for your reviewer:

I kinda guessed where to put the SVGs and what to name them as they need to be publicly addressable. I'm open to changing there location/names.

## Testing

Built the docker container and was able to get the images to work, no other functionality has changed.

After

### CODE REVIEW

**Comment by michael-genson** [comment]
LGTM, though I'm a little confused why this works; @boc-the-git any idea why this seems to work and it didn't work on your initial PR? Maybe because they're svgs?

Initial PWA shortcuts PR: https://github.com/mealie-recipes/mealie/pull/3255

**Comment by Choromanski** [comment]
It looks like they only defined the app icons and didn't define any shortcut icons.

[w3c documentation example](https://w3c.github.io/manifest/#creating-shortcuts)

**Comment by michael-genson** [comment]
In boc's initial commit he did, he just removed them since they didn't work: https://github.com/mealie-recipes/mealie/pull/3255/commits/00f32ae5a8b151c39ae3ec7d509341c2f2953ce5

Reverted here: https://github.com/mealie-recipes/mealie/pull/3255/commits/1a158d13e1ed0bd3c1c05f9bd962eb4eb8c74430

**Comment by Choromanski** [comment]
It's super finicky when I tried putting the "type" field in it didn't work.

**Comment by boc-the-git** [comment]
> LGTM, though I'm a little confused why this works; @boc-the-git any idea why this seems to work and it didn't work on your initial PR? Maybe because they're svgs?
> 
> Initial PWA shortcuts PR: https://github.com/mealie-recipes/mealie/pull/3255

No idea. Maybe I tried png only and it didn't work. Maybe something else.

This PR makes me extremely happy! Well done @Choromanski

**Comment by michael-genson** [comment]
??? That's so bizarre. Okay good enough for me. Thanks! The icons have been bugging me forever

**Review by michael-genson — APPROVED** [review]

**Review by boc-the-git — APPROVED** [review]

**Pull request merged**
