### PR TITLE
feat: Add Additional SMTP Headers to Decrease Spam Score

### LINKED ISSUE #3028: [BUG] - No Date header in test email?
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

I am trying to setup SMTP service via my local email server. I use Postfix with OpenDMARC and OpenDKIM.
When mealie tries to send a test email, OpenDMARC complains with this error:
``RFC5322 requirement error: not exactly one Date field``
I was wondering, how to check if Mealie added a date header to the email?

[From RFC5322](https://datatracker.ietf.org/doc/html/rfc5322#section-3.6):
"The only required header fields are the origination date field and the originator address field(s).  All other header fields are
   syntactically optional."

### Steps to Reproduce

In Site Settings, under the Email section, try to send an email with "Test" button

### Please provide relevant logs

ERROR: 22-Jan-24 12:42:18       (550, b'5.7.1 Command rejected')

### Mealie Version

Docker image 1.0 release

### Deployment

Docker (Linux)

### Additional Deployment Details

_No response_

### PR DESCRIPTION
**Pull request by michael-genson**
## What type of PR is this?

_(REQUIRED)_

- bug
- feature

## What this PR does / why we need it:

_(REQUIRED)_

Adds missing headers detailed in https://github.com/mealie-recipes/mealie/discussions/2993 (and https://github.com/mealie-recipes/mealie/issues/3028) to decrease our spam score

## Which issue(s) this PR fixes:

_(REQUIRED)_

Closes https://github.com/mealie-recipes/mealie/discussions/2993
Fixes https://github.com/mealie-recipes/mealie/issues/3028

### CODE REVIEW

**Review by Kuchenpirat — APPROVED** [review]
Looks good 👍

**Comment by be-joeri** [comment]
Hi!

Thanks for implementing this, spam score looks much better now.

Two remarks:
- the message ID is missing brackets (< >), guess you can just add them when you generate the message_id variable on lines 48 and 52.
- the plain text part is shown in mail clients following RFC 2046 (Gmail for example). The last part of a multipart message is considered best and is preferred, so you should add the text part first and the html part second. You can fix this by swapping lines 44 and 45.

Keep up the good work!

**Comment by boc-the-git** [comment]
Hey @be-joeri, good detailed feedback there, thanks. This sounds like a great opportunity to get your first PR merged! :)
The README has a section on contributing as a starting point if needed, and we welcome all the help!
The Discord is also very friendly if you had a specific thing you needed help with while working through the process.

**Comment by be-joeri** [comment]
Hi @boc-the-git,

Thanks for suggesting to create a PR. 
I'm not really a coder and the whole process is new to me, so reading instructions and setting things up took a lot more time than the actual change :)
I created https://github.com/mealie-recipes/mealie/pull/3094 . Please let me know if I made a mistake somewhere so I can take that into account next time.

**Comment by boc-the-git** [comment]
Well done @be-joeri!! First PR is a great milestone. Hopefully the first of many (be they for Mealie or other projects).

Given you mention your lack of familiarity with doing stuff like this, if there's anything in the docs that could be made more clear, from your experience, please let us know!

**Pull request merged**
