### PR TITLE
fix: Follow redirects during scraping

### PR DESCRIPTION
**Pull request by zeskeertwee**
## What type of PR is this?

- bug

## What this PR does / why we need it:

URL's from albert heijn such as `https://www.ah.nl/r/1195504` are shared from the albert heijn app, and fail to scrape because they return a 301 moved permanently which eventually leads to `https://www.ah.nl/allerhande/recept/R-R1195504/romige-linguine-met-brie-artisjok-en-parmaham`, which scrapes perfectly fine. This is fixed by telling `httpx` to follow redirects.
This allows users to directly import recepies from the app instead of having to first follow the redirects in a browser.

## Which issue(s) this PR fixes:

URL's like `https://www.ah.nl/r/1195504` from the albert heijn app fail to scrape

## Testing

The aformentioned URL now scrapes fine as the redirects are followed, as seen in the logs:
```
INFO     2024-07-10T14:23:26 - HTTP Request: GET https://www.ah.nl/r/1195504 "HTTP/1.1 301 Moved Permanently"
INFO     2024-07-10T14:23:27 - HTTP Request: GET https://www.ah.nl/allerhande/recept/R-R1195504 "HTTP/1.1 301 Moved Permanently"
INFO     2024-07-10T14:23:27 - HTTP Request: GET https://www.ah.nl/allerhande/recept/R-R1195504/romige-linguine-met-brie-artisjok-en-parmaham "HTTP/1.1 200 OK"
```

### CODE REVIEW

**Comment by michael-genson** [comment]
LGTM, other than the lint issue. Once that's fixed we can merge

**Comment by zeskeertwee** [comment]
Thanks, formatting has been fixed in 1cf28a659dc148ab81bb39120564b5e8351574cc

**Review by michael-genson — APPROVED** [review]
Looks good, thanks!

More info about the dismissed security advisory, copy-pasted for visibility:

This is part of the recipe scraper code so it's expected that we fetch user-supplied URLs. We don't authenticate these requests, so there is no elevated permissions, and we validate the HTML before importing a recipe

**Comment by niekniek89** [comment]
i have this issue with the latest version also with dishes from ah.nl.
what can i do?

**Pull request merged**
