### PR TITLE
Create shoppinglist from weekly mealplan

### PR DESCRIPTION
**Pull request by danielpalstra**
This PR adds a create button that adds all recipes from the mealplan to a new shopping list. 

image

### CODE REVIEW

**Comment by michael-genson** [comment]
Does the create button have other functions, or is it only for adding to the shopping list? If it's the latter, we should probably name it something like "Add to Shopping List". You can use the "formatListCheck" or "cartCheck" icon to match the shopping list icon

**Comment by danielpalstra** [comment]
> Does the create button have other functions, or is it only for adding to the shopping list? If it's the latter, we should probably name it something like "Add to Shopping List". You can use the "formatListCheck" or "cartCheck" icon to match the shopping list icon

I would like to change the title of the button, but I couldn't find a way to set the text yet.

**Comment by danielpalstra** [comment]
I've found an example so I renamed the Create button to "Add to Shopping List".

**Comment by hay-kot** [comment]
Hey! Thanks for the PR. My main concern with this implementation is that it's possible to create a shopping list with duplicates since the scroller has some overlap when paging through the meal planner. I also think that that we should be able to add to an existing Shopping list since I've heard most folks have two or three shoppings lists they always keep around. 

Maybe we could implement a dialog that would let them select recipes from the current page and then add those to a selected shopping list or create one?

**Pull request closed without merging**
