### PR TITLE
fix: User creation through API when signups are supposed to be diabled 

### LINKED ISSUE #1724: [v1.0.0b] - Possible to register a new user using the api when signups are disabled
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

**Overview** 
On my personal system I have set  `- ALLOW_SIGNUP=false` in the docker-compose file as I do not wish anyone to be able to register without myself orchestrating this. 

I was playing around with the swagger docs at /docs and I noticed I could sign up very easily there with no authentication and log in.

**Steps to reproduce**
1. Set `- ALLOW_SIGNUP=false` in your docker compose file and use `docker-compose up` to start the system
2. Navigate to the swagger docs `http://deployment-url:deployment-port/docs`
3. Use the `/api/users/register` endpoint to create a new user

**Expected Result**
- A user cannot be created unless the user of the API is authenticated as an admin

**Actual Result**
- A new user is created and can be used to login to Mealie

### Deployment

Docker (Linux)

### Deployment Details

**Details**
Version: v1.0.0beta-4
Build: 13850cda1f9cb02a8c788030ba6cfa96bba33571
Application Mode: Production
Demo Status: Not Demo
API Port: 9000
API Docs: Enabled
Database Type: sqlite
Recipe Scraper Version: 14.11.0

**Checks**
Secure Site: No
Server Side Base URL: Yes
LDAP Ready: No
Email Configured: No
Docker Volumes: success

### PR DESCRIPTION
**Pull request by Kuchenpirat**
As described in #1724 registering an user through the api possible even though ALLOW_SIGNUP is set to false. This allowes anybody to create users and new groups on mealie instances.

## What type of PR is this?
- bug

## What this PR does / why we need it:

The behaviour above is possible because: 
- Mealie is only checking whether signups are disabled and if the group token is _None_ or an empty string. 
- If this is the case the user registration service is called which directly creates a new group if a group name is provided. 

This PR changes the order of the if statements and always checks the group token first if one is provided. If the Group token provided does not match the token of an existing group, the user will not be created. 

## Which issue(s) this PR fixes:

Fixes #1724 

## Special notes for your reviewer:

First PR on mealie so not too familiar with the code base. If i have missed some obvious stuff i am sorry. 

## Testing

- Tested user creation through API (with and without signups enabled)
- Tested user creation through invite link and normal register button. 
- Tests are currently broken on my system, so i could not do them.

### CODE REVIEW

**Comment by hay-kot** [comment]
Hey! This looks great, I think it's worth adding some automated testing for this to ensure we don't have a regression. Is that something you're up for looking into? I'm not sure how complicated it may be.

**Comment by Kuchenpirat** [comment]
Added some tests. 
Not 100% sure if they are sufficient but they should at least catch the #1724 bug

**Comment by Kuchenpirat** [comment]
don't know why the automations are failing especially on the one file where i just have shuffeled code around

**Comment by Kuchenpirat** [comment]
formating (black) should pass now.

**Comment by Kuchenpirat** [comment]
lol, did i really forget the .py in the filename 🤣

**Comment by michael-genson** [comment]
Haha no sweat

**Review by michael-genson — APPROVED** [review]

**Review by hay-kot — APPROVED** [review]

**Comment by RemakingEden** [comment]
Hey @Kuchenpirat, cheers for fixing this issue! :)

**Pull request merged**
