### PR TITLE
Impove Parser card

### PR DESCRIPTION
**Pull request by Miroito**
# Changes
- Moved the original text to a less awkward position since ingredient sections are now kept. See screenshots.

## Before
image

## After
image

### CODE REVIEW

**Comment by michael-genson** [comment]
Huh, when I added the data back in I didn't actually know the frontend rendered the titles here. I like this better

**Comment by hay-kot** [comment]
Does this remove the display text if they're collapsed? Sometimes the % will be high and it will default to collapsed, but I still read through incase the sentence is structured weird and I know there will be problems.

**Comment by Miroito** [comment]
> Does this remove the display text if they're collapsed? Sometimes the % will be high and it will default to collapsed, but I still read through incase the sentence is structured weird and I know there will be problems.

I have added a fade in transition lines 53 to 57 to still show the original text. You can pull the branch to have a look at it if you like.

**Comment by hay-kot** [comment]
> I have added a fade in transition lines 53 to 57 to still show the original text. You can pull the branch to have a look at it if you like.

I'm apparently not so good at the reading comprehension. I will take a look at this tomorrow morning, thanks!

**Comment by hay-kot** [comment]
Really dig the fade, thanks for this one! 🚀

**Pull request merged**
