### PR TITLE
Added "cookbook" filter to recipe pagination to serve frontend

### LINKED ISSUE #1605: [v1.0.0b] - Sort no longer working on Recents and Cookbooks pages
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Sort functionality is no longer working on Recents or Cookbooks pages. It's still working fine in All Recipes, Categories, Tags and Tools pages.

### Deployment

Docker (Synology)

### Deployment Details

```
**Details**
Version: v1.0.0beta-4 (nightly)
Build: 56eb0bca7142715984c8028c4c881f086e979564
Application Mode: Production
Demo Status: Not Demo
API Port: 9000
API Docs: Enabled
Database Type: sqlite
Recipe Scraper Version: 14.13.0

**Checks**
Secure Site: Yes
Server Side Base URL: Yes
LDAP Ready: No
Email Configured: Yes
Docker Volumes: success
```

### PR DESCRIPTION
**Pull request by michael-genson**
Partially resolves #1605 by fixing the cookbook sort. I added a cookbook filter to recipe pagination which applies the appropriate category, tag, and tool filters (it uses the same `_category_tag_filters` function the cookbook repo uses). Consequently, this means you can use the filter API to additionally filter the recipes in a cookbook (though I'm not sure why you'd want to).

Not sure of a good way to add sorting back to recent recipes, so I've left it alone for now.

### CODE REVIEW

**Comment by michael-genson** [comment]
This cache hates me...
Tests work okay locally

**Comment by michael-genson** [comment]
FYI @hay-kot this is ready :) test should pass if the cache stops being moody

**Comment by hay-kot** [comment]
Tested Locally LGTM 🚀

**Comment by epheterson** [comment]
Thanks for this fix! In hindsight I don’t think we need to worry about sorting on the recents page since it already has a logical sort for its context, so no need to revisit that part.

**Pull request merged**
