### PR TITLE
feat: Remove OCR Support

### LINKED ISSUE #2394: [Nightly] - OCR Editor Fails to Copy Text to Selected Field in Instructions
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

This behavior occurs on the "Instructions" tab in the OCR editor:

The directions in the OCR editor indicate that the workflow should be to use the rectangular selection tool to select a portion of the image that contains the text you want to capture, then select the field you want the text to go into, then click the selection box again to copy the text to the field.

Despite following these instructions (assuming I interpreted them correctly), the text is not copied into the field.  The text appears below the image, indicating that the OCR is working, but no text is added to the selected field.

I verified this on both Chrome and Firefox using both my own container and the demo instance on mealie.io.

Hypothesis on why this is happening:

I think what's going on is that the Steps fields are not being made editable on the page as they are when manually creating a recipe or after importing from a URL.  Clicking on the Step 1 field that is there by default displays the green checkmark, as it does when the recipe card isn't in edit mode. This makes it appear that the field is being selected, when in fact it's just hiding the step. Also missing are any options to delete, merge, or reorder the fields.

This makes the Bulk Add option unusable as well.  While it does capture the text and allow you to edit it, saving the bulk add leaves you with a number of steps filled in with no way to modify them to reorganize, consolidate, or format the text. The logic on how it creates and populates the fields seems unpredictable, and since you have to close the OCR editor to edit any of the fields, it's difficult to wrangle it. Editing the fields needs to be possible in the OCR editor because you don't have access to the OCR data or the image (unless it's also the cover image) outside the OCR editor.

### Deployment

Unraid

### Deployment Details

_No response_

### LINKED ISSUE #2424: [vomni-nightly] - OCR recipe creation doesn't honor group settings.
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

When creating a recipe from image (OCR), and savings it, it does not get the default group settings (public recipe, disable comments, landscape, etc).
This could be linked to https://github.com/hay-kot/mealie/issues/2394.

### Deployment

Docker (Linux)

### Deployment Details

_No response_

### LINKED ISSUE #2437: [v1.0.0b] - OCR recipe batch creation capped at 10 recipes
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Creating more than 10 recipes using the API (`POST /api/recipes/create-ocr`) without renaming them will cause an internal server error.

Log:
```
INFO:     10.42.1.101:55522 - "POST /api/recipes/create-ocr HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 748, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: recipes.slug, recipes.group_id
```

Adding a `name` parameter to the API (like the one `POST /api/recipes` has) would help fixing the issue by explicitly giving a name to the created recipe.

Also, the API could return a 409 in these situations instead of simply returning a generic server error. That would help diagnose problems when using the API.

This issue also makes Mealie's Frontend UI fail silently when creating more than 10 OCR recipes without changing their title.

### Deployment

Other

### Deployment Details

Both components deployed to Kubernetes (k3s):
* API image: hkotel/mealie:api-nightly
* Frontend image: hkotel/mealie:frontend-nightly

Build info:
**Details**
Version: nightly
Build: 674774d073ff6e9aba90a8291a11e8e55ced44f6
Application Mode: Production
Demo Status: Not Demo
API Port: 9000
API Docs: Enabled
Database Type: sqlite
Recipe Scraper Version: 14.36.0

**Checks**
Secure Site: Yes
Server Side Base URL: Yes
LDAP Ready: No
Email Configured: No
Docker Volumes: success

### LINKED ISSUE #2451: Created a test recipe, now unable to delete it
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] I have checked for existing issues that have been resolved in v1-beta

### What is the issue you are experiencing?

I found the OCR feature and tested it out. For some reason it refused to save and just kept giving me an error message, but I don't have an issue with that. Back on the recipe homepage I now have this created by that test...

Screenshot 2023-07-09 at 23 32 53

But I can't find a way to delete it. When I click the 'Edit' button i get this 404

Screenshot 2023-07-09 at 23 33 03

Is there some way I'm missing where I can get rid of it?

### Deployment

Docker (Linux)

### Deployment Details

_No response_

### Mealie Version

v1.0.0beta-5

### PR DESCRIPTION
**Pull request by michael-genson**
## What type of PR is this?

_(REQUIRED)_

- cleanup

## What this PR does / why we need it:

_(REQUIRED)_

This removes OCR from Mealie. This is done for a few reasons:
- The current OCR implementation is half-baked; there are several issues with it that usually make it easier to just type your recipes manually
- Discussion in Discord heavily leans towards no one using it, or it not working (which is the closest thing we have to actual usage data)
- Removing it helps focus contributor attention (it's currently one of the more complex features with the most bugs)
- Removing it drastically lowers build times, container sizes, and resource usage

## Which issue(s) this PR fixes:

_(REQUIRED)_

Closes https://github.com/mealie-recipes/mealie/issues/2394
Closes https://github.com/mealie-recipes/mealie/issues/2424
Closes https://github.com/mealie-recipes/mealie/issues/2437
Closes https://github.com/mealie-recipes/mealie/issues/2451

## Special notes for your reviewer:

_(fill-in or delete this section)_

I removed the `is_ocr_recipe` field from the schema, but left it in the db (since we can't easily remove it from sqlite). I also left all of the translations and the mdi-icons, in case we're able to re-purpose them. Happy to remove those if needed.

### CODE REVIEW

**Review by Kuchenpirat — COMMENTED** [review]
Maybe run `make docs` to remove the ocr endpoints from the api references

**Review by Kuchenpirat — APPROVED** [review]
Looks Good.
Will not merge yet, as maybe somebody with more experience should have another go

**Review by hay-kot — APPROVED** [review]
LGTM

LET'S GOOOOOOOOOO

**Comment by Miroito** [comment]
I know we have our differences and as the person that wrote this feature and lost interest in maintaining it due to multiple factors, I agree fully with this decision from your point of view and I respect it. I'll continue to use mealie as long as it is the better open source recipe manager which I think that it still is.
Sometimes goals are not achieved and it's more courageous to give up.

**Pull request merged**
