### PR TITLE
fix: 3892 missing parameter documentation

### LINKED ISSUE #3892: [BUG] - SQLite to PostgreSQL FATAL: role "root" does not exist
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

I am trying to migrate from the SQLite to PostgreSQL database for performance reasons, I have thousands of recipes and the SQLite is bogged down when searching recipes, ~30 seconds to load anything. 

The backup restoration is failing.

### Steps to Reproduce

1) Install mealie postgres version https://docs.mealie.io/documentation/getting-started/installation/postgres/ 
2) Upload backup
3) In postgres alter mealie as SUPERUSER
4) attempt to restore backup

### Please provide relevant logs

Mealie:
(Background on this error at: https://sqlalche.me/e/20/e3q8)
500 Internal Server Error "POST /api/admin/backups/mealie_2024.07.15.00.15.08.zip/restore HTTP/1.1"

PostgreSQL:
[1090] FATAL: role "root" does not exist

### Mealie Version

_No response_

### Deployment

Docker (Linux)

### Additional Deployment Details

Running it on a raspberry pi

### PR DESCRIPTION
**Pull request by VTerret**
## What type of PR is this?

- documentation

## What this PR does / why we need it:

This push request adds a missing parameter on the postgres example which causes an error log in the docker console.

## Which issue(s) this PR fixes:

Fixes https://github.com/mealie-recipes/mealie/issues/3892

### CODE REVIEW

**Comment by boc-the-git** [comment]
Please provide a meaningful title to the pull request.

**Comment by michael-genson** [comment]
Is there a reason not to update the healthcheck instead? So configuration is easier if users want to customize it for some reason. e.g.
`test: ["CMD", "pg_isready", "-U", "$$POSTGRES_USER", "-d", "$$POSTGRES_DB"]`

(Also if you could verify this works, I'm just basing this off the linked stackoverflow thread)

**Comment by boc-the-git** [comment]
Hey @VTerret, just confirming this is something you intend to come back to?

**Comment by VTerret** [comment]
I have tested this configuration on my own installation. It fix the **FATAL: role "root" does not exist**. 
I don't know enough about docker to suggest a better solution to this problem, but if there is one, I'll understand if my PR is rejected.

**Comment by michael-genson** [comment]
Did you try using my suggestion above?

**Comment by VTerret** [comment]
It seems that it doesn't work. 
- with  test: `["CMD", "pg_isready", "-U", "$$POSTGRES_USER", "-d", "$$POSTGRES_DB"]` log became `FATAL:  role "$POSTGRES_USER" does not exist`
- with  `test: ["CMD", "pg_isready", "-U", "$POSTGRES_USER", "-d", "$POSTGRES_DB"]` log is still `FATAL: role "root" does not exist`
- If I try directly `test: pg_isready -U $$POSTGRES_USER` container doesn't start at all.

**Comment by michael-genson** [comment]
Got it, in that case let's just stick with what you have. Thanks for checking!

**Review by michael-genson — APPROVED** [review]

**Pull request merged**
