### PR TITLE
feat: Add environment variables to enable ingredients/steps placeholders

### PR DESCRIPTION
**Pull request by choikangjae**
## What type of PR is this?

_(REQUIRED)_

- documentation
- feature

## What this PR does / why we need it:

_(REQUIRED)_

## Which issue(s) this PR fixes:

This PR allows seasoned users to disable placeholders when creating a recipe manually. When a user set `False` to environment variables, `ENABLE_INGREDIENTS_PLACEHOLDER` and `ENABLE_STEPS_PLACEHOLDER`, placeholders won't be placed. 

Screenshot_20240710_181746

Screenshot_20240710_192835

Default value is `True`, so not to change the app's previous behavior. And only texts will be affected, not cards even if they are disabled, so users don't need to click `+Add` to create the first ingredient or step.

## Special notes for your reviewer:

N/A

## Testing

Ran `task py:check`

### CODE REVIEW

**Comment by boc-the-git** [comment]
My first thought is whether an environment variable is really the best option here, or whether it should be a group setting :thinking: 
I also don't think we should necessarily have the step/ingredient created at all, if they're blank :thinking:

**Comment by boc-the-git** [comment]
Merged mealie-next, which hopefully re-evaluates the PR title

**Comment by choikangjae** [comment]
At first, I was trying to add these options as a preference from a user or an admin which can be set from a web UI, but I couldn't find a suitable place to put these options. Existed environment variables like `ALLOW_SIGNUP`, `DEFAULT_GROUP`, or `DAILY_SCHEDULE_TIME` made me think this is where the preferences go to. If it is not the place for them, could you instruct me where should I put them?

Secondly, I thought pre-made blank step/ingredient cards are convenient (to me), I have to add those anyway if I want to make a proper recipe. So it would be better not adding cards at all? It was convenient to add cards for my workflow, but since I don't know how the other users use it, I will follow your guidance.

**Comment by Kuchenpirat** [comment]
i second bocs opinion that this is something we should implement via a group setting.

They can be found at `/group` or by clicking on your profile picture in the top left and then *Group Settings*

**Comment by choikangjae** [comment]
It seems that group settings are the best suitable place for these options. Thanks for letting me know. I will open new PR after I changed it.

**Pull request closed without merging**
