### PR TITLE
Intial OIDC login

### PR DESCRIPTION
**Pull request by TomCranitch**
## What type of PR is this?

- documentation
- feature

## What this PR does / why we need it:

This PR adds OIDC login.

## Which issue(s) this PR fixes:

This has been mentioned a few times (e.g. #1197)

## Special notes for your reviewer:

 - I'm not too sure what kind of tests would be good here (if any)
 - I've added authlib as it can use JWKS to verify the OIDC JWT
 - I'm not confident that what I've done in index.vue is the best approach, but I needed a way to override the user that is returned from the OIDC provider with the mealie user

## Testing

Have tested by hand using authentik.

## Release Notes

```release-note
Adds OIDC login for SSO.
```

## Remain todos

 - Documentation
 - Testing?? (I'm looking for suggestions here)
 - Linting

### CODE REVIEW

**Comment by BhasherBEL** [comment]
Hi! Why was this PR closed ? Is there a problem with this implementation ? I'm interested by OIDC in mealie, and willing to help implement it.

**Comment by RedCider** [comment]
This is a feature that has been asked for many times and should be taken into account. LDAP seems kind of a 1990ies solution and kind of cracking a nut with a sledge hammer since most oidc solutions like for example authelia don't need LDAP and thus are far easier to set up in a docker environment. Also oidc offers more flexibilty and LDAP also could be integrated with most oidc providers.

**Comment by disconn3ct** [comment]
It's closed because stalebot is a thin excuse to ignore contributions and @hay-kot has said repeatedly they don't care about auth.

**Comment by hay-kot** [comment]
> It's closed because stalebot is a thin excuse to ignore contributions 

How much of my free time do you think you're entitled to? Should I block it off on my calendar?  This isn't a job I get paid for, it's something I do for free for the community, sometimes I can't get to things. Instead of complaining about it, why don't you sign up to help? We need people to review PRs, triage issues, and help in the discord.

>  @hay-kot has said repeatedly they don't care about auth.

This is ridiculous. 

I've repeatedly said that _none of the maintainers care about SSO_ because none of us use it. If you want to see something in the project, submit a PR and like I've said repeatedly, submit it with tests. There is _literally_ a PR we intend to merge directly above your comment that includes full testing so we can ensure that the feature works going forward.

**Pull request closed without merging**
