### PR TITLE
fix: Update user-agent

### LINKED ISSUE #3524: [SCRAPER] - www.colruyt.be/nl/lekker-koken recipe scraping returns failed to scrape url
### First Check

- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I have verified that this issue _is not_ related to the underlying library
[hhyrsev/recipe-scrapers](https://github.com/hhursev/recipe-scrapers) by **1)** checking
the [debugger](https://demo.mealie.io/g/home/r/create/debug) and data is returned, **2)**
verifying that there _are_ errors in the log related to application level code, or
**3)** verified that the site provides recipe data, or is otherwise supported by
[hhyrsev/recipe-scrapers](https://github.com/hhursev/recipe-scrapers)

- [X] This issue can be replicated on the demo site (https://demo.mealie.io/)

### Please provide 1-5 example URLs that are having errors

https://www.colruyt.be/nl/lekker-koken/recept/scampi-torpedo-met-chimichurri
https://www.colruyt.be/nl/lekker-koken/recept/one-pot-pasta-met-4-groenten

### Please provide your logs for the Mealie container `docker logs <container-id> > mealie.logs`

INFO     2024-04-27T12:29:09 - HTTP Request: GET https://www.colruyt.be/nl/lekker-koken/recept/scampi-torpedo-met-chimichurri "HTTP/1.1 456 "
ERROR    2024-04-27T12:29:09 - Recipe Scraper was unable to extract a recipe from https://www.colruyt.be/nl/lekker-koken/recept/scampi-torpedo-met-chimichurri
ERROR    2024-04-27T12:29:09 - failed to scrape url during bulk url import https://www.colruyt.be/nl/lekker-koken/recept/scampi-torpedo-met-chimichurri
Traceback (most recent call last):
ERROR    2024-04-27T12:29:09 - 400: {'details': 'BAD_RECIPE_DATA'}
fastapi.exceptions.HTTPException: 400: {'details': 'BAD_RECIPE_DATA'}
    raise HTTPException(status.HTTP_400_BAD_REQUEST, {"details": ParserErrors.BAD_RECIPE_DATA.value})
  File "/app/mealie/services/scraper/scraper.py", line 37, in create_from_url
    recipe, _ = await create_from_url(url, self.translator)
  File "/app/mealie/services/scraper/recipe_bulk_scraper.py", line 88, in _do

### Deployment

Docker (Synology)

### PR DESCRIPTION
**Pull request by ndragon798**
## What type of PR is this?
- bug

## Which issue(s) this PR fixes: #3524

Tested via spinning it up in docker-compose

### CODE REVIEW

**Comment by boc-the-git** [comment]
Worth noting @hay-kot has a very similar PR: https://github.com/mealie-recipes/mealie/pull/3457
It looks like it'd be more future-proof, though on the face of it he hasn't finished testing it.

**Comment by ndragon798** [comment]
I'm looking at adding a more robust UA rotation method but I wanted a simple fix for now. There quite a few api's that we could pull a list of current UAs automatically and just rotate through those so we don't get an 1 user-agent banned.

**Comment by hay-kot** [comment]
https://github.com/mealie-recipes/mealie/pull/3457 - Is tested. (failing CI is unrelated to PR)

> I'm looking at adding a more robust UA rotation method but I wanted a simple fix for now. There quite a few api's that we could pull a list of current UAs automatically and just rotate through those so we don't get an 1 user-agent banned.

Is an interesting idea. If you implement this, I'd suggest letting it be user configurable either by a comma separated list via ENV variable or a JSON file or something and then using a factory pattern or something to pick one at random which one to use.

**Comment by ndragon798** [comment]
Closing the PR since the other one was merged.

**Pull request closed without merging**
