### PR TITLE
fix: sort recent recipes by created_at instead of date_added

### PR DESCRIPTION
**Pull request by michael-genson**
This is a fix for #1410. I changed the default sort to use created_at, and I also wrote it in the frontend to explicitly sort by created_at in case we ever change the default behavior.

Optionally we can switch this to the updated timestamp, which might be more desirable in recent, but I'm not sure. Regardless it's in the schema now so it's an easy toggle.

### CODE REVIEW

**Comment by michael-genson** [comment]
These backend tests are out to get me

**Comment by michael-genson** [comment]
@hay-kot do you know why the backend tests are failing? Am I doing something wrong? AFAIK they shouldn't be failing, the tests are running fine on my machine, and the errors seem package related

**Comment by hay-kot** [comment]
The cache for the runner is probably broken, you can try rebasing and pick up the dependency changes and bust the cache.

**Comment by michael-genson** [comment]
Ah I didn't think about the dependency changes, thanks!

**Pull request merged**
