### PR TITLE
fix: Incorrect date format in Add to mealplan modal

### LINKED ISSUE #4598: [BUG] - Date format hint is incorrect (and probably irrelevant)
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

When adding recipe to the meal plan, date field in dialog box shows a hint `MM/DD/YYYY format`, but then date itself is shown in format `2024-11-13`.
I see that hint changes with change in language, but format of the date is not.
Additionally, AFAICT this field is not intended to be manually edited (`readonly="readonly"`) so maybe whole hint should be dropped?

Setup used to reproduce:
Firefox 128.4.0esr on Windows 11. 
System date format dd.mm.yyyy

### Steps to Reproduce

1. Three dots on recipe
2. Add to Plan
3. Select any date

### Please provide relevant logs

UI only, no logs

### Mealie Version

2.2.0

### Deployment

Docker (Synology)

### Additional Deployment Details

_No response_

### PR DESCRIPTION
**Pull request by Saireddy1369**
## What type of PR is this?

bug

## What this PR does / why we need it:

This PR resolves an issue with the date field hint in the "Add to Plan" dialog box. The hint initially displayed the date format as `MM/DD/YYYY`, which was inconsistent with the actual date format (`YYYY-MM-DD`). This inconsistency could confuse users, especially since the field is `readonly` and uses a date picker. 

The hint has now been completely removed to simplify the UI and avoid redundancy.

## Changes made:

- Removed the `:hint` and `persistent-hint` properties from the `<v-text-field>` component for the date picker in the "Add to Plan" dialog box.
- Simplified the UI by removing the unnecessary hint, as the field is not intended for manual input.

## Which issue(s) this PR fixes:

Fixes #4598

## Special notes for your reviewer:

- Please verify that removing the hint does not introduce any regressions in other parts of the application.
- Ensure that the date picker functionality works as expected across different languages and locales.

## Testing:

- Tested on the demo site using Firefox 128.4.0esr on Windows 11.
- Verified that the hint has been successfully removed.
- Confirmed that the date picker field remains `readonly` and continues to function as intended.

### CODE REVIEW

**Comment by michael-genson** [comment]
On mobile, so apologies if this is an obvious question: does the user type the date into this field manually, or do they use a date picker?

If it's a date picker, should we just get rid of the hint? I'm not sure what purpose it serves otherwise

**Comment by Saireddy1369** [comment]
Yes, it's a date picker. Initially, I thought of avoiding confusion by matching the hint format with the displayed date format, so I made changes to use date-format-hint-yyyy-mm-dd.

However, I completely agree that the hint might be unnecessary since the field isn't meant for manual input. I’ll update my changes to remove the hint altogether to simplify and avoid redundancy. Thank you for pointing it out!

**Comment by Saireddy1369** [comment]
Updated the code to remove the date picker hint in the 'Add to Plan' dialog. The field uses a date picker, so the hint was unnecessary. Please review the changes. Thanks!

**Review by michael-genson — APPROVED** [review]
Thank you!

**Pull request merged**
