### PR TITLE
feat: Added feature to limit mealplan data by date range

### PR DESCRIPTION
**Pull request by vshulcz**
## What type of PR is this?

_(REQUIRED)_

- feature

## What this PR does / why we need it:

_(REQUIRED)_

This PR addresses a TODO found in the project code to limit the retrieval of meal plan data to a specific date range, rather than fetching all meal plans.

### Changes:
- **File Modified**: `mealie/repos/repository_meals.py`
  - **RepositoryMeals**: Added a new method `get_meals_by_date_range(start_date: datetime, end_date: datetime)` to filter meal plans within a specified date range.
- **File Modified**: `mealie/services/event_bus_service/event_bus_listeners.py`
  - **WebhookEventListener**: Updated to use the new method to fetch meal plans only within the range defined by `webhook_start_dt` and `webhook_end_dt`.

This change ensures that only relevant meal plan data is included in webhook notifications, aligning with the initial TODO comment.

## Which issue(s) this PR fixes:

_(REQUIRED)_

This PR closes a minor improvement related to a TODO in the codebase.

## Special notes for your reviewer:

_(fill-in or delete this section)_

Please ensure that the `EventWebhookData` class is always provided with valid `webhook_start_dt` and `webhook_end_dt` values to ensure that the date range filtering functions correctly.

### CODE REVIEW

**Comment by vshulcz** [comment]
@hay-kot I've applied the required formatting with ruff. It's ready for review!

**Comment by vshulcz** [comment]
@hay-kot Sorry, I forgot to check with ruff lint. Please try again.

**Comment by vshulcz** [comment]
Hi @hay-kot,
I wanted to check if there are any concerns or changes needed from my side to get this merged. Please let me know if there's anything I can do to assist with moving this forward. Thanks for your time!

**Review by michael-genson — CHANGES_REQUESTED** [review]
Looks good! Would you be able to add a few tests for this?

**Comment by vshulcz** [comment]
Hey, @michael-genson! Tests have been added as requested. However, the change doesn't seem to introduce any breaking changes. Can you please confirm if the breaking-change label is still necessary?

**Comment by michael-genson** [comment]
Great! I'll take a look when I'm back at my desk.

> Can you please confirm if the breaking-change label is still necessary

Technically this is a breaking change because there could be existing integrations which depend on all meal plans being sent, and now only the relevant ones are.

**Review by michael-genson — APPROVED** [review]
Looks great, thanks again!

**Pull request merged**
