### PR TITLE
feat: Added support for plural_name for foods

### PR DESCRIPTION
**Pull request by Choromanski**
Destroyed PR #4129 when trying to rebase. Was just easier to create a new PR.

## What type of PR is this?

- feature

## What this PR does / why we need it:

This PR allows the seeder to import plural names for foods.
This allows for new user have cleaner ingredient lists without having to do any additional configuration.

## Which issue(s) this PR fixes:

N/A

## Special notes for your reviewer:

1. This work was discussed in #3933 
2. If anything is done that causes issues with crowdin let me know and I can work to resolve it.
3. I only provided plurals for foods that would normally be the unit (ex. 1 watermelon)
4. I sorted the list by keys so that I could de-duplicate easier
5. I also removed some words that were duplicated in there UK equivalent (ex. aubergine/eggplant, broad/fava beans, icing/powdered sugar)
6. Any comments or recommendations would be greatly appreciated

## Testing

Ran a fresh install and all of the plural ingredients were seeded properly:
image

### CODE REVIEW

**Comment by Choromanski** [comment]
@hay-kot could you try to review this before you update Crowdin again and I have to redo it?

If you don't think this PR is a good idea just let me know.

**Review by hay-kot — APPROVED** [review]
LGTM, I think we'd just need to double check Crowdin after merge just be ready to revert in case anything goes wrong. Will wait for another approval before I merge.

**Comment by Choromanski** [comment]
@michael-genson looked at the original PR but I believe was waiting for your approval.

**Review by michael-genson — APPROVED** [review]
Yup, LGTM too!

**Pull request merged**
