### PR TITLE
Fix docker-compose files

### PR DESCRIPTION
**Pull request by tribut**
Frontend-Dockerfile is now simply called `Dockerfile`, the [build/target parameter](https://docs.docker.com/compose/compose-file/compose-file-v3/#target) has been added in compose file version 3.4.

### CODE REVIEW

**Comment by hay-kot** [comment]
Hey! Thanks for the PR. The docker-compose file you updated is for development, but the dockerfile is the one used for production, as such it won't hot reload when making changes, so it doesn't really apply to the compose file.

Did you want to take a stab at implementing the hot reload for the docker-compose.dev.yml?

**Comment by tribut** [comment]
Hey, thanks for taking the time. I really just wanted to get *any* dev environment working so I could try out some things. I understand that `frontend/Dockerfile` is meant for production, but I don't think there is another Dockerfile available right now?
With the changes from this PR, `make docker-dev` doesn't throw any errors at least. Is there some other way to get a mealie-next dev environment (using Docker) I'm missing?

**Comment by hay-kot** [comment]
> but I don't think there is another Dockerfile available right now?

Correct. I haven't been using docker for development for some time, so I haven't been keeping it up to date. 

> With the changes from this PR, make docker-dev doesn't throw any errors at least. 

The image will build just fine and "work" but for development in the Frontend, you'll need to create a new Dockerfile to enable hot reloading. If you're only doing backend stuff, you probably don't need to worry about this for now.

**Comment by hay-kot** [comment]
Closing since I think this PR is addressing the issue. Still a WIP though. 

- #756

**Pull request closed without merging**
