### PR TITLE
docs: Fix en-GB translations for backups

### PR DESCRIPTION
**Pull request by boc-the-git**
## What type of PR is this?

- cleanup
- documentation

## What this PR does / why we need it:

Fix doco

## Which issue(s) this PR fixes:

None.

## Special notes for your reviewer:

Ironically the correct en-GB "translation" is just the same as en-US for this.

### CODE REVIEW

**Comment by michael-genson** [comment]
I don't think changes here will work, I'm pretty sure they have to be done through Crowdin:
https://crowdin.com/project/mealie

**Comment by boc-the-git** [comment]
Fair enough! I was uncertain, but figured as they end up here that it would be sufficient. I'll look to make the changes in crowdin when time allows.

**Comment by michael-genson** [comment]
iirc Crowdin will replace any manual changes made (other than en-US changes)

**Comment by boc-the-git** [comment]
I've just made the change on Crowdin, so I'll close this PR.

FYI @hay-kot, it shows that you added the erroneous translation 22 days ago. Not sure if my change here will undo something you were working on..
image

**Pull request closed without merging**
