### PR TITLE
feat: Insert instruction step above or below. #3731

### PR DESCRIPTION
**Pull request by derpferd**
## What type of PR is this?

- feature

## What this PR does / why we need it:

- This PR fixes the feature requested in #3731.
- It adds two options to the step menu: "Insert Above" and "Insert Below"
- Each option adds a new step either above or below the current step.

Screenshot 2024-06-12 at 9 22 01 PM

## Which issue(s) this PR fixes:

Fixes #3731

## Testing

- Tested in UI
- Added step above first step, below last step and above and below a step in the middle.

### CODE REVIEW

**Review by michael-genson — COMMENTED** [review]
Overall looks good. Would you be able to add the same functionality to ingredients? I feel like we should have this for both

**Comment by derpferd** [comment]
Yes, will do.

**Comment by derpferd** [comment]
Added same functionality to ingredients in latest commit

**Review by michael-genson — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
